//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/locale/Colors.java
//
//

#import <jVanila/jvanila.h>

@interface Colors : NSObject {
}

@end

typedef Colors ComHomeawayHomeawayplacesLocaleColors;
