//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/locale/Strings.java
//
//

#import <jVanila/jvanila.h>

@interface Strings : NSObject {
}

+ (NSString *)place_list_search_in;
+ (NSString *)place_list_search_nearby;
+ (NSString *)place_list_search_places;
+ (NSString *)place_list_no_results;
+ (NSString *)place_list_no_favs;
+ (NSString *)place_list_no_internet;
+ (NSString *)place_list_unrecoverable_nw_error;
+ (NSString *)place_list_search_retry;
+ (NSString *)map_poi_click_message;
@end

typedef Strings ComHomeawayHomeawayplacesLocaleStrings;
