//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/locale/Strings.java
//
//

#import "Strings.h"

@implementation Strings

static NSString * Strings_place_list_search_in_ = @"place_list_search_in";
static NSString * Strings_place_list_search_nearby_ = @"place_list_search_nearby";
static NSString * Strings_place_list_search_places_ = @"place_list_search_places";
static NSString * Strings_place_list_no_results_ = @"place_list_no_results";
static NSString * Strings_place_list_no_favs_ = @"place_list_no_favs";
static NSString * Strings_place_list_no_internet_ = @"place_list_no_internet";
static NSString * Strings_place_list_unrecoverable_nw_error_ = @"place_list_unrecoverable_nw_error";
static NSString * Strings_place_list_search_retry_ = @"place_list_search_retry";
static NSString * Strings_map_poi_click_message_ = @"map_poi_click_message";

+ (NSString *)place_list_search_in {
  return Strings_place_list_search_in_;
}

+ (NSString *)place_list_search_nearby {
  return Strings_place_list_search_nearby_;
}

+ (NSString *)place_list_search_places {
  return Strings_place_list_search_places_;
}

+ (NSString *)place_list_no_results {
  return Strings_place_list_no_results_;
}

+ (NSString *)place_list_no_favs {
  return Strings_place_list_no_favs_;
}

+ (NSString *)place_list_no_internet {
  return Strings_place_list_no_internet_;
}

+ (NSString *)place_list_unrecoverable_nw_error {
  return Strings_place_list_unrecoverable_nw_error_;
}

+ (NSString *)place_list_search_retry {
  return Strings_place_list_search_retry_;
}

+ (NSString *)map_poi_click_message {
  return Strings_map_poi_click_message_;
}

@end
