//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/binders/PlaceListItemDataBinder.java
//
//

#import "PlaceListItemDataBinder.h"
#import "Place.h"
#import "R.h"
#import "IPlaceListItemView.h"

@implementation PlaceListItemDataBinder

static NSString * PlaceListItemDataBinder_RATING_COLOR_GOOD_ = @"#64DD17";
static NSString * PlaceListItemDataBinder_RATING_COLOR_AVG_ = @"#CCFF90";
static NSString * PlaceListItemDataBinder_RATING_COLOR_BELOW_AVG_ = @"#FFAB40";
static NSString * PlaceListItemDataBinder_RATING_COLOR_POOR_ = @"#DD2C00";
static NSString * PlaceListItemDataBinder_FAVORITE_TINT_COLOR_ = @"#FF4081";

@synthesize mNumberUtils = mNumberUtils_;

+ (NSString *)RATING_COLOR_GOOD {
  return PlaceListItemDataBinder_RATING_COLOR_GOOD_;
}

+ (NSString *)RATING_COLOR_AVG {
  return PlaceListItemDataBinder_RATING_COLOR_AVG_;
}

+ (NSString *)RATING_COLOR_BELOW_AVG {
  return PlaceListItemDataBinder_RATING_COLOR_BELOW_AVG_;
}

+ (NSString *)RATING_COLOR_POOR {
  return PlaceListItemDataBinder_RATING_COLOR_POOR_;
}

+ (NSString *)FAVORITE_TINT_COLOR {
  return PlaceListItemDataBinder_FAVORITE_TINT_COLOR_;
}

- (id)initWithIPlaceListItemView:(id<IPlaceListItemView>)view {
  return [super initWithId:view];
}

- (void)onCreate {
  [super onCreate];
  mNumberUtils_ = [mMobilePlatformFactory_ getNumberUtils];
}

- (BOOL)onBindWithObjects:(id)_objects,... {
	NSMutableArray *objects = [[NSMutableArray alloc] init];
	va_list args;
	va_start(args, _objects);
	for (id arg = _objects; arg != nil; arg = va_arg(args, id)) {
		[objects addObject:arg];
	}
	va_end(args);
	return [self onBindWithNSArray:objects];
}

-(BOOL)onBindWithNSArray:(NSArray *)objects {
  [self onBindPlaceWithPlace:(Place *) objects[0]];
  return YES;
}

- (void)onBindPlaceWithPlace:(Place *)place {
  [((id<IPlaceListItemView>) ((id<IPlaceListItemView>) [self getView])) addTagWithId:place];
  [((id<IPlaceListItemView>) ((id<IPlaceListItemView>) [self getView])) setPlaceLabelWithNSString:place.name];
  [((id<IPlaceListItemView>) ((id<IPlaceListItemView>) [self getView])) setPlaceAddressWithNSString:place.address];
  NSString *categoryLabel = @"";
  NSString *iconUrl = nil;
  if (place.category != nil) {
    categoryLabel = place.category;
    iconUrl = place.imageUrl;
  }
  [((id<IPlaceListItemView>) ((id<IPlaceListItemView>) [self getView])) setCategoryLabelWithNSString:categoryLabel];
  [((id<IPlaceListItemView>) ((id<IPlaceListItemView>) [self getView])) setCategoryIconWithNSString:iconUrl];
  if (place.isFavorite) {
    Resource *resource = [[Resource alloc] initWithInt:R_drawable_outline_favorite_black_24 withNSString:@"outline_favorite_black_24" withNSString:@"drawable"];
    [((id<IPlaceListItemView>) ((id<IPlaceListItemView>) [self getView])) setFavoriteIconWithResource:resource withNSString:PlaceListItemDataBinder_FAVORITE_TINT_COLOR_];
  }
  else {
    Resource *resource = [[Resource alloc] initWithInt:R_drawable_outline_favorite_border_black_24 withNSString:@"outline_favorite_border_black_24" withNSString:@"drawable"];
    [((id<IPlaceListItemView>) ((id<IPlaceListItemView>) [self getView])) setFavoriteIconWithResource:resource withNSString:PlaceListItemDataBinder_FAVORITE_TINT_COLOR_];
  }
  if (place.distanceToInterest > 0) {
    NSString *distanceLabel = [NSString stringWithFormat:@"%@m", [mNumberUtils_ stringifyIntWithInt:place.distanceToInterest]];
    [((id<IPlaceListItemView>) ((id<IPlaceListItemView>) [self getView])) setAndShowDistanceLabelWithNSString:distanceLabel];
  }
  else {
    [((id<IPlaceListItemView>) ((id<IPlaceListItemView>) [self getView])) hideDistanceLabel];
  }
  if (place.rating > 0) {
    NSString *ratingLabel = [mNumberUtils_ stringifyFloatWithFloat:place.rating];
    NSString *ratingColor = [self getRatingColorWithInt:(int) place.rating];
    [((id<IPlaceListItemView>) ((id<IPlaceListItemView>) [self getView])) setAndShowRatingIconAndLabelWithNSString:ratingLabel withNSString:ratingColor];
  }
  else {
    [((id<IPlaceListItemView>) ((id<IPlaceListItemView>) [self getView])) hideRatingIconAndLabel];
  }
  if (place.showWebsite) {
    if (![mStringUtils_ isNullOrEmptyWithNSString:place.websiteUrl]) {
      [((id<IPlaceListItemView>) ((id<IPlaceListItemView>) [self getView])) setAndShowWebsiteUrlWithNSString:place.websiteUrl];
    }
    [((id<IPlaceListItemView>) ((id<IPlaceListItemView>) [self getView])) hideDivider];
  }
  else {
    [((id<IPlaceListItemView>) ((id<IPlaceListItemView>) [self getView])) hideWebsiteUrl];
    [((id<IPlaceListItemView>) ((id<IPlaceListItemView>) [self getView])) showDivider];
  }
}

- (NSString *)getRatingColorWithInt:(int)rating {
  NSString *color = PlaceListItemDataBinder_RATING_COLOR_POOR_;
  if (rating >= PlaceListItemDataBinder_RATING_GOOD_LB) {
    color = PlaceListItemDataBinder_RATING_COLOR_GOOD_;
  }
  else if (rating >= PlaceListItemDataBinder_RATING_AVG_LB) {
    color = PlaceListItemDataBinder_RATING_COLOR_AVG_;
  }
  else if (rating >= PlaceListItemDataBinder_RATING_BELOW_AVG_LB) {
    color = PlaceListItemDataBinder_RATING_COLOR_BELOW_AVG_;
  }
  return color;
}

- (void)copyAllPropertiesTo:(id)copy {
  
  PlaceListItemDataBinder *typedCopy = (PlaceListItemDataBinder *) copy;
  typedCopy.mNumberUtils = mNumberUtils_;
}

@end
