//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/binders/PlaceListItemDataBinder.java
//
//

@class IOSObjectArray;
@class Place;

@protocol IPlaceListItemView;

#import <jVanila/jvanila.h>


#define PlaceListItemDataBinder_RATING_AVG_LB 6
#define PlaceListItemDataBinder_RATING_BELOW_AVG_LB 4
#define PlaceListItemDataBinder_RATING_GOOD_LB 8

@interface PlaceListItemDataBinder : DataBinder {
 @public
  id<INumberUtils> mNumberUtils_;
}

@property (nonatomic, strong) id<INumberUtils> mNumberUtils;

+ (NSString *)RATING_COLOR_GOOD;
+ (NSString *)RATING_COLOR_AVG;
+ (NSString *)RATING_COLOR_BELOW_AVG;
+ (NSString *)RATING_COLOR_POOR;
+ (NSString *)FAVORITE_TINT_COLOR;
- (id)initWithIPlaceListItemView:(id<IPlaceListItemView>)view;
- (void)onCreate;
- (BOOL)onBindWithObjects:(id)objects,... NS_REQUIRES_NIL_TERMINATION;
- (BOOL)onBindWithNSArray:(NSArray *)objects;
- (void)onBindPlaceWithPlace:(Place *)place;
- (NSString *)getRatingColorWithInt:(int)rating;
@end

typedef PlaceListItemDataBinder ComHomeawayHomeawayplacesBindersPlaceListItemDataBinder;
