//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/foursquare/sync/dtos/FSCategoryDTO.java
//
//

@class FSIconDTO;

#import <jVanila/jvanila.h>


#define FSCategoryDTO_serialVersionUID 1

@interface FSCategoryDTO : DataObject {
 @public
  NSString *CRUDOperation_;
  NSString *id__;
  NSString *name_;
  NSString *pluralName_;
  NSString *shortName_;
  FSIconDTO *icon_;
  BOOL primary_;
}

@property (nonatomic, copy) NSString *CRUDOperation;
@property (nonatomic, copy) NSString *id_;
@property (nonatomic, copy) NSString *name;
@property (nonatomic, copy) NSString *pluralName;
@property (nonatomic, copy) NSString *shortName;
@property (nonatomic, strong) FSIconDTO *icon;
@property (nonatomic, assign) BOOL primary;

+ (NSString *)CLASS_NAME;
- (id)init;
@end

typedef FSCategoryDTO ComHomeawayHomeawayplacesFoursquareSyncDtosFSCategoryDTO;
