//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/foursquare/sync/dtos/FSGroupDTO.java
//
//



#import <jVanila/jvanila.h>


#define FSGroupDTO_serialVersionUID 1

@interface FSGroupDTO : DataObject {
 @public
  NSString *CRUDOperation_;
  id<IGenericList> items_;
}

@property (nonatomic, copy) NSString *CRUDOperation;
@property (nonatomic, strong) id<IGenericList> items;

+ (NSString *)CLASS_NAME;
- (id)init;
@end

typedef FSGroupDTO ComHomeawayHomeawayplacesFoursquareSyncDtosFSGroupDTO;
