//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/foursquare/sync/dtos/FSHearNowDTO.java
//
//

#import "FSHearNowDTO.h"

@implementation FSHearNowDTO

static NSString * CLASS_NAME_;

@synthesize CRUDOperation = CRUDOperation_;
@synthesize count = count_;
@synthesize summary = summary_;

+ (NSString *)CLASS_NAME {
  return CLASS_NAME_;
}

- (id)init {
  if ((self = [super init])) {
    CRUDOperation_ = @"U";
  }
  return self;
}

+ (void)initialize {
  if (self == [FSHearNowDTO class]) {
    {
      CLASS_NAME_ = NSStringFromClass([FSHearNowDTO class]);
    }
  }
}

- (void)copyAllPropertiesTo:(id)copy {
  
  FSHearNowDTO *typedCopy = (FSHearNowDTO *) copy;
  typedCopy.CRUDOperation = CRUDOperation_;
  typedCopy.count = count_;
  typedCopy.summary = summary_;
}

@end
