//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/foursquare/sync/dtos/FSHearNowDTO.java
//
//

#import <jVanila/jvanila.h>


#define FSHearNowDTO_serialVersionUID 1

@interface FSHearNowDTO : DataObject {
 @public
  NSString *CRUDOperation_;
  int count_;
  NSString *summary_;
}

@property (nonatomic, copy) NSString *CRUDOperation;
@property (nonatomic, assign) int count;
@property (nonatomic, copy) NSString *summary;

+ (NSString *)CLASS_NAME;
- (id)init;
@end

typedef FSHearNowDTO ComHomeawayHomeawayplacesFoursquareSyncDtosFSHearNowDTO;
