//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/foursquare/sync/dtos/FSIconDTO.java
//
//

#import "FSCategoryDTO.h"
#import "FSIconDTO.h"

@implementation FSIconDTO

static NSString * CLASS_NAME_;

@synthesize CRUDOperation = CRUDOperation_;
@synthesize prefix = prefix_;
@synthesize suffix = suffix_;

+ (NSString *)CLASS_NAME {
  return CLASS_NAME_;
}

- (id)init {
  if ((self = [super init])) {
    CRUDOperation_ = @"U";
  }
  return self;
}

+ (void)initialize {
  if (self == [FSIconDTO class]) {
    {
      CLASS_NAME_ = NSStringFromClass([FSCategoryDTO class]);
    }
  }
}

- (void)copyAllPropertiesTo:(id)copy {
  
  FSIconDTO *typedCopy = (FSIconDTO *) copy;
  typedCopy.CRUDOperation = CRUDOperation_;
  typedCopy.prefix = prefix_;
  typedCopy.suffix = suffix_;
}

@end
