//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/foursquare/sync/dtos/FSItemDTO.java
//
//

@class FSVenueDTO;


#import <jVanila/jvanila.h>


#define FSItemDTO_serialVersionUID 1

@interface FSItemDTO : DataObject {
 @public
  NSString *CRUDOperation_;
  NSString *referralId_;
  FSVenueDTO *venue_;
  id<IGenericList> tips_;
}

@property (nonatomic, copy) NSString *CRUDOperation;
@property (nonatomic, copy) NSString *referralId;
@property (nonatomic, strong) FSVenueDTO *venue;
@property (nonatomic, strong) id<IGenericList> tips;

+ (NSString *)CLASS_NAME;
- (id)init;
@end

typedef FSItemDTO ComHomeawayHomeawayplacesFoursquareSyncDtosFSItemDTO;
