//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/foursquare/sync/dtos/FSLocationDTO.java
//
//



#import <jVanila/jvanila.h>


#define FSLocationDTO_serialVersionUID 1

@interface FSLocationDTO : DataObject {
 @public
  NSString *CRUDOperation_;
  NSString *address_;
  NSString *crossStreet_;
  double lat_;
  double lng_;
  int distance_;
  int postalCode_;
  NSString *cc_;
  NSString *city_;
  NSString *state_;
  NSString *country_;
  id<IGenericList> formattedAddress_;
  NSString *entity_uuid_;
}

@property (nonatomic, copy) NSString *CRUDOperation;
@property (nonatomic, copy) NSString *address;
@property (nonatomic, copy) NSString *crossStreet;
@property (nonatomic, assign) double lat;
@property (nonatomic, assign) double lng;
@property (nonatomic, assign) int distance;
@property (nonatomic, assign) int postalCode;
@property (nonatomic, copy) NSString *cc;
@property (nonatomic, copy) NSString *city;
@property (nonatomic, copy) NSString *state;
@property (nonatomic, copy) NSString *country;
@property (nonatomic, strong) id<IGenericList> formattedAddress;
@property (nonatomic, copy) NSString *entity_uuid;

+ (NSString *)CLASS_NAME;
- (id)init;
- (void)setCSVRepresentationOfformattedAddressWithNSString:(NSString *)csvformattedAddress
                                              withNSString:(NSString *)delimiter;
- (NSString *)getCSVRepresentationOfformattedAddressWithNSString:(NSString *)delimiter;
@end

typedef FSLocationDTO ComHomeawayHomeawayplacesFoursquareSyncDtosFSLocationDTO;
