//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/foursquare/sync/dtos/FSMetaDTO.java
//
//

#import <jVanila/jvanila.h>


#define FSMetaDTO_serialVersionUID 1

@interface FSMetaDTO : DataObject {
 @public
  NSString *CRUDOperation_;
  int code_;
  NSString *requestId_;
}

@property (nonatomic, copy) NSString *CRUDOperation;
@property (nonatomic, assign) int code;
@property (nonatomic, copy) NSString *requestId;

+ (NSString *)CLASS_NAME;
- (id)init;
@end

typedef FSMetaDTO ComHomeawayHomeawayplacesFoursquareSyncDtosFSMetaDTO;
