//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/foursquare/sync/dtos/FSMetaDTO.java
//
//

#import "FSMetaDTO.h"

@implementation FSMetaDTO

static NSString * CLASS_NAME_;

@synthesize CRUDOperation = CRUDOperation_;
@synthesize code = code_;
@synthesize requestId = requestId_;

+ (NSString *)CLASS_NAME {
  return CLASS_NAME_;
}

- (id)init {
  if ((self = [super init])) {
    CRUDOperation_ = @"U";
  }
  return self;
}

+ (void)initialize {
  if (self == [FSMetaDTO class]) {
    {
      CLASS_NAME_ = NSStringFromClass([FSMetaDTO class]);
    }
  }
}

- (void)copyAllPropertiesTo:(id)copy {
  
  FSMetaDTO *typedCopy = (FSMetaDTO *) copy;
  typedCopy.CRUDOperation = CRUDOperation_;
  typedCopy.code = code_;
  typedCopy.requestId = requestId_;
}

@end
