//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/foursquare/sync/dtos/FSPriceDTO.java
//
//

#import <jVanila/jvanila.h>


#define FSPriceDTO_serialVersionUID 1

@interface FSPriceDTO : DataObject {
 @public
  NSString *CRUDOperation_;
  int tier_;
  NSString *message_;
  NSString *currency_;
}

@property (nonatomic, copy) NSString *CRUDOperation;
@property (nonatomic, assign) int tier;
@property (nonatomic, copy) NSString *message;
@property (nonatomic, copy) NSString *currency;

+ (NSString *)CLASS_NAME;
- (id)init;
@end

typedef FSPriceDTO ComHomeawayHomeawayplacesFoursquareSyncDtosFSPriceDTO;
