//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/foursquare/sync/dtos/FSResultDTO.java
//
//

@class FSMetaDTO;
@class FSResponseDTO;

#import <jVanila/jvanila.h>


#define FSResultDTO_serialVersionUID 1

@interface FSResultDTO : DataObject {
 @public
  NSString *CRUDOperation_;
  FSMetaDTO *meta_;
  FSResponseDTO *response_;
}

@property (nonatomic, copy) NSString *CRUDOperation;
@property (nonatomic, strong) FSMetaDTO *meta;
@property (nonatomic, strong) FSResponseDTO *response;

+ (NSString *)CLASS_NAME;
- (id)init;
@end

typedef FSResultDTO ComHomeawayHomeawayplacesFoursquareSyncDtosFSResultDTO;
