//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/foursquare/sync/dtos/FSResponseDTO.java
//
//

#import "FSResponseDTO.h"
#import "FSResultDTO.h"

@implementation FSResponseDTO

static NSString * CLASS_NAME_;

@synthesize CRUDOperation = CRUDOperation_;
@synthesize venues = venues_;

+ (NSString *)CLASS_NAME {
  return CLASS_NAME_;
}

- (id)init {
  if ((self = [super init])) {
    CRUDOperation_ = @"U";
  }
  return self;
}

+ (void)initialize {
  if (self == [FSResponseDTO class]) {
    {
      CLASS_NAME_ = NSStringFromClass([FSResultDTO class]);
    }
  }
}

- (void)copyAllPropertiesTo:(id)copy {
  
  FSResponseDTO *typedCopy = (FSResponseDTO *) copy;
  typedCopy.CRUDOperation = CRUDOperation_;
  typedCopy.venues = venues_;
}

@end
