//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/foursquare/sync/dtos/FSResultDTO.java
//
//

#import "FSMetaDTO.h"
#import "FSResponseDTO.h"
#import "FSResultDTO.h"

@implementation FSResultDTO

static NSString * CLASS_NAME_;

@synthesize CRUDOperation = CRUDOperation_;
@synthesize meta = meta_;
@synthesize response = response_;

+ (NSString *)CLASS_NAME {
  return CLASS_NAME_;
}

- (id)init {
  if ((self = [super init])) {
    CRUDOperation_ = @"U";
  }
  return self;
}

+ (void)initialize {
  if (self == [FSResultDTO class]) {
    {
      CLASS_NAME_ = NSStringFromClass([FSResultDTO class]);
    }
  }
}

- (void)copyAllPropertiesTo:(id)copy {
  
  FSResultDTO *typedCopy = (FSResultDTO *) copy;
  typedCopy.CRUDOperation = CRUDOperation_;
  typedCopy.meta = meta_;
  typedCopy.response = response_;
}

@end
