//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/foursquare/sync/dtos/FSResponseDTO.java
//
//



#import <jVanila/jvanila.h>


#define FSResponseDTO_serialVersionUID 1

@interface FSResponseDTO : DataObject {
 @public
  NSString *CRUDOperation_;
  id<IGenericList> venues_;
}

@property (nonatomic, copy) NSString *CRUDOperation;
@property (nonatomic, strong) id<IGenericList> venues;

+ (NSString *)CLASS_NAME;
- (id)init;
@end

typedef FSResponseDTO ComHomeawayHomeawayplacesFoursquareSyncDtosFSResponseDTO;
