//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/foursquare/sync/dtos/FSRequestDTO.java
//
//



#import <jVanila/jvanila.h>


#define FSRequestDTO_serialVersionUID 1

@interface FSRequestDTO : DataObject {
 @public
  NSString *CRUDOperation_;
  NSString *query_;
  id<IGenericMap> params_;
}

@property (nonatomic, copy) NSString *CRUDOperation;
@property (nonatomic, copy) NSString *query;
@property (nonatomic, strong) id<IGenericMap> params;

+ (NSString *)CLASS_NAME;
- (id)init;
@end

typedef FSRequestDTO ComHomeawayHomeawayplacesFoursquareSyncDtosFSRequestDTO;
