//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/foursquare/sync/dtos/FSRequestDTO.java
//
//

#import "FSRequestDTO.h"

@implementation FSRequestDTO

static NSString * CLASS_NAME_;

@synthesize CRUDOperation = CRUDOperation_;
@synthesize query = query_;
@synthesize params = params_;

+ (NSString *)CLASS_NAME {
  return CLASS_NAME_;
}

- (id)init {
  if ((self = [super init])) {
    CRUDOperation_ = @"U";
  }
  return self;
}

+ (void)initialize {
  if (self == [FSRequestDTO class]) {
    {
      CLASS_NAME_ = NSStringFromClass([FSRequestDTO class]);
    }
  }
}

- (void)copyAllPropertiesTo:(id)copy {
  
  FSRequestDTO *typedCopy = (FSRequestDTO *) copy;
  typedCopy.CRUDOperation = CRUDOperation_;
  typedCopy.query = query_;
  typedCopy.params = params_;
}

@end
