//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/foursquare/sync/dtos/FSStatsDTO.java
//
//

#import "FSStatsDTO.h"
#import "FSVenueHoursDTO.h"

@implementation FSStatsDTO

static NSString * CLASS_NAME_;

@synthesize CRUDOperation = CRUDOperation_;
@synthesize checkinsCount = checkinsCount_;
@synthesize usersCount = usersCount_;
@synthesize tipCount = tipCount_;

+ (NSString *)CLASS_NAME {
  return CLASS_NAME_;
}

- (id)init {
  if ((self = [super init])) {
    CRUDOperation_ = @"U";
  }
  return self;
}

+ (void)initialize {
  if (self == [FSStatsDTO class]) {
    {
      CLASS_NAME_ = NSStringFromClass([FSVenueHoursDTO class]);
    }
  }
}

- (void)copyAllPropertiesTo:(id)copy {
  
  FSStatsDTO *typedCopy = (FSStatsDTO *) copy;
  typedCopy.CRUDOperation = CRUDOperation_;
  typedCopy.checkinsCount = checkinsCount_;
  typedCopy.usersCount = usersCount_;
  typedCopy.tipCount = tipCount_;
}

@end
