//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/foursquare/sync/dtos/FSTipDTO.java
//
//

#import "FSTipDTO.h"

@implementation FSTipDTO

static NSString * CLASS_NAME_;

@synthesize CRUDOperation = CRUDOperation_;
@synthesize createdAt = createdAt_;
@synthesize text = text_;
@synthesize type = type_;
@synthesize canonicalUrl = canonicalUrl_;

+ (NSString *)CLASS_NAME {
  return CLASS_NAME_;
}

- (id)init {
  if ((self = [super init])) {
    CRUDOperation_ = @"U";
  }
  return self;
}

+ (void)initialize {
  if (self == [FSTipDTO class]) {
    {
      CLASS_NAME_ = NSStringFromClass([FSTipDTO class]);
    }
  }
}

- (void)copyAllPropertiesTo:(id)copy {
  
  FSTipDTO *typedCopy = (FSTipDTO *) copy;
  typedCopy.CRUDOperation = CRUDOperation_;
  typedCopy.createdAt = createdAt_;
  typedCopy.text = text_;
  typedCopy.type = type_;
  typedCopy.canonicalUrl = canonicalUrl_;
}

@end
