//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/foursquare/sync/dtos/FSVenueDTO.java
//
//

@class FSHearNowDTO;
@class FSLocationDTO;
@class FSPriceDTO;
@class FSStatsDTO;
@class FSVenueHoursDTO;


#import <jVanila/jvanila.h>


#define FSVenueDTO_serialVersionUID 1

@interface FSVenueDTO : DataObject {
 @public
  NSString *CRUDOperation_;
  NSString *id__;
  NSString *name_;
  FSLocationDTO *location_;
  id<IGenericList> categories_;
  FSStatsDTO *stats_;
  NSString *url_;
  FSPriceDTO *price_;
  float rating_;
  FSVenueHoursDTO *hours_;
  FSHearNowDTO *hearNow_;
  BOOL isFavorite_;
  BOOL showWebsite_;
}

@property (nonatomic, copy) NSString *CRUDOperation;
@property (nonatomic, copy) NSString *id_;
@property (nonatomic, copy) NSString *name;
@property (nonatomic, strong) FSLocationDTO *location;
@property (nonatomic, strong) id<IGenericList> categories;
@property (nonatomic, strong) FSStatsDTO *stats;
@property (nonatomic, copy) NSString *url;
@property (nonatomic, strong) FSPriceDTO *price;
@property (nonatomic, assign) float rating;
@property (nonatomic, strong) FSVenueHoursDTO *hours;
@property (nonatomic, strong) FSHearNowDTO *hearNow;
@property (nonatomic, assign) BOOL isFavorite;
@property (nonatomic, assign) BOOL showWebsite;

+ (NSString *)CLASS_NAME;
- (id)init;
@end

typedef FSVenueDTO ComHomeawayHomeawayplacesFoursquareSyncDtosFSVenueDTO;
