//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/foursquare/sync/dtos/FSVenueHoursDTO.java
//
//

#import <jVanila/jvanila.h>


#define FSVenueHoursDTO_serialVersionUID 1

@interface FSVenueHoursDTO : DataObject {
 @public
  NSString *CRUDOperation_;
  NSString *status_;
  BOOL isOpen_;
  BOOL isLocalHoliday_;
}

@property (nonatomic, copy) NSString *CRUDOperation;
@property (nonatomic, copy) NSString *status;
@property (nonatomic, assign) BOOL isOpen;
@property (nonatomic, assign) BOOL isLocalHoliday;

+ (NSString *)CLASS_NAME;
- (id)init;
@end

typedef FSVenueHoursDTO ComHomeawayHomeawayplacesFoursquareSyncDtosFSVenueHoursDTO;
