//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/foursquare/sync/dtos/FSVenueHoursDTO.java
//
//

#import "FSVenueHoursDTO.h"

@implementation FSVenueHoursDTO

static NSString * CLASS_NAME_;

@synthesize CRUDOperation = CRUDOperation_;
@synthesize status = status_;
@synthesize isOpen = isOpen_;
@synthesize isLocalHoliday = isLocalHoliday_;

+ (NSString *)CLASS_NAME {
  return CLASS_NAME_;
}

- (id)init {
  if ((self = [super init])) {
    CRUDOperation_ = @"U";
  }
  return self;
}

+ (void)initialize {
  if (self == [FSVenueHoursDTO class]) {
    {
      CLASS_NAME_ = NSStringFromClass([FSVenueHoursDTO class]);
    }
  }
}

- (void)copyAllPropertiesTo:(id)copy {
  
  FSVenueHoursDTO *typedCopy = (FSVenueHoursDTO *) copy;
  typedCopy.CRUDOperation = CRUDOperation_;
  typedCopy.status = status_;
  typedCopy.isOpen = isOpen_;
  typedCopy.isLocalHoliday = isLocalHoliday_;
}

@end
