//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/foursquare/sync/dtos/FSVenueListDTO.java
//
//



#import <jVanila/jvanila.h>


#define FSVenueListDTO_serialVersionUID 1

@interface FSVenueListDTO : DataObject {
 @public
  NSString *CRUDOperation_;
  id<IGenericList> venus_;
}

@property (nonatomic, copy) NSString *CRUDOperation;
@property (nonatomic, strong) id<IGenericList> venus;

+ (NSString *)CLASS_NAME;
- (id)init;
@end

typedef FSVenueListDTO ComHomeawayHomeawayplacesFoursquareSyncDtosFSVenueListDTO;
