//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/foursquare/sync/dtos/FSVenueDTO.java
//
//

#import "FSHearNowDTO.h"
#import "FSLocationDTO.h"
#import "FSPriceDTO.h"
#import "FSStatsDTO.h"
#import "FSVenueDTO.h"
#import "FSVenueHoursDTO.h"

@implementation FSVenueDTO

static NSString * CLASS_NAME_;

@synthesize CRUDOperation = CRUDOperation_;
@synthesize id_ = id__;
@synthesize name = name_;
@synthesize location = location_;
@synthesize categories = categories_;
@synthesize stats = stats_;
@synthesize url = url_;
@synthesize price = price_;
@synthesize rating = rating_;
@synthesize hours = hours_;
@synthesize hearNow = hearNow_;
@synthesize isFavorite = isFavorite_;
@synthesize showWebsite = showWebsite_;

+ (NSString *)CLASS_NAME {
  return CLASS_NAME_;
}

- (id)init {
  if ((self = [super init])) {
    CRUDOperation_ = @"U";
  }
  return self;
}

+ (void)initialize {
  if (self == [FSVenueDTO class]) {
    {
      CLASS_NAME_ = NSStringFromClass([FSVenueHoursDTO class]);
    }
  }
}

- (void)copyAllPropertiesTo:(id)copy {
  
  FSVenueDTO *typedCopy = (FSVenueDTO *) copy;
  typedCopy.CRUDOperation = CRUDOperation_;
  typedCopy.id_ = id__;
  typedCopy.name = name_;
  typedCopy.location = location_;
  typedCopy.categories = categories_;
  typedCopy.stats = stats_;
  typedCopy.url = url_;
  typedCopy.price = price_;
  typedCopy.rating = rating_;
  typedCopy.hours = hours_;
  typedCopy.hearNow = hearNow_;
  typedCopy.isFavorite = isFavorite_;
  typedCopy.showWebsite = showWebsite_;
}

@end
