//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/domain/PlacesApi.java
//
//

#import "PlacesApi.h"
#import "PlacesProvider.h"

@implementation PlacesApi

static PlacesProvider * PlacesApi_sProvider_;

+ (PlacesProvider *)sProvider {
  return PlacesApi_sProvider_;
}

+ (void)setSProviderWithPlacesProvider:(PlacesProvider *)sProvider {
  PlacesApi_sProvider_ = sProvider;
}

+ (void)withProviderWithPlacesProvider:(PlacesProvider *)provider {
  PlacesApi_sProvider_ = provider;
}

+ (PlacesProvider *)provider {
  return PlacesApi_sProvider_;
}

@end
