//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/domain/PlacesApi.java
//
//

@class PlacesProvider;

#import <jVanila/jvanila.h>

@interface PlacesApi : NSObject {
}

+ (PlacesProvider *)sProvider;
+ (void)setSProviderWithPlacesProvider:(PlacesProvider *)sProvider;
+ (void)withProviderWithPlacesProvider:(PlacesProvider *)provider;
+ (PlacesProvider *)provider;
@end

typedef PlacesApi ComHomeawayHomeawayplacesDomainPlacesApi;
