//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/domain/PlaceModifiedEvent.java
//
//

#import "Place.h"
#import "PlaceModifiedEvent.h"

@implementation PlaceModifiedEvent

static NSString * PlaceModifiedEvent_CLASS_NAME_;

@synthesize place = place_;

+ (NSString *)CLASS_NAME {
  return PlaceModifiedEvent_CLASS_NAME_;
}

- (id)initWithPlace:(Place *)place {
  if ((self = [super init])) {
    self.place = place;
  }
  return self;
}

+ (void)initialize {
  if (self == [PlaceModifiedEvent class]) {
    {
      PlaceModifiedEvent_CLASS_NAME_ = NSStringFromClass([PlaceModifiedEvent class]);
    }
  }
}

- (void)copyAllPropertiesTo:(id)copy {
  
  PlaceModifiedEvent *typedCopy = (PlaceModifiedEvent *) copy;
  typedCopy.place = place_;
}

@end
