//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/domain/PlacesContext.java
//
//



#import <jVanila/jvanila.h>

@interface PlacesContext : NSObject {
 @public
  VanilaLocation *poi_;
  int fetchLimit_;
  int cacheLimit_;
}

@property (nonatomic, strong) VanilaLocation *poi;
@property (nonatomic, assign) int fetchLimit;
@property (nonatomic, assign) int cacheLimit;

- (id)init;
@end

typedef PlacesContext ComHomeawayHomeawayplacesDomainPlacesContext;
