//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/domain/PlaceSearchResultEvent.java
//
//

#import "Place.h"
#import "PlaceSearchResultEvent.h"

@implementation PlaceSearchResultEvent

static NSString * PlaceSearchResultEvent_CLASS_NAME_;

@synthesize query = query_;
@synthesize placeList = placeList_;
@synthesize failureResponse = failureResponse_;

+ (NSString *)CLASS_NAME {
  return PlaceSearchResultEvent_CLASS_NAME_;
}

- (id)initWithNSString:(NSString *)query
withIGenericList:(id<IGenericList>)placeList
withFailureResponseDTO:(FailureResponseDTO *)failureResponse {
  if ((self = [super init])) {
    self.query = query;
    self.placeList = placeList;
    self.failureResponse = failureResponse;
  }
  return self;
}

+ (void)initialize {
  if (self == [PlaceSearchResultEvent class]) {
    {
      PlaceSearchResultEvent_CLASS_NAME_ = NSStringFromClass([PlaceSearchResultEvent class]);
    }
  }
}

- (void)copyAllPropertiesTo:(id)copy {
  
  PlaceSearchResultEvent *typedCopy = (PlaceSearchResultEvent *) copy;
  typedCopy.query = query_;
  typedCopy.placeList = placeList_;
  typedCopy.failureResponse = failureResponse_;
}

@end
