//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/domain/Place.java
//
//

#import "Place.h"

@implementation Place

static NSString * Place_CLASS_NAME_;

@synthesize CRUDOperation = CRUDOperation_;
@synthesize placeId = placeId_;
@synthesize name = name_;
@synthesize address = address_;
@synthesize latLng = latLng_;
@synthesize categoryId = categoryId_;
@synthesize category = category_;
@synthesize websiteUrl = websiteUrl_;
@synthesize imageUrl = imageUrl_;
@synthesize distanceToInterest = distanceToInterest_;
@synthesize rating = rating_;
@synthesize isFavorite = isFavorite_;
@synthesize showWebsite = showWebsite_;

+ (NSString *)CLASS_NAME {
  return Place_CLASS_NAME_;
}

- (id)init {
  if ((self = [super init])) {
    CRUDOperation_ = @"U";
  }
  return self;
}

- (BOOL)isEqualsToWithIComparableObject:(id<IComparableObject>)o {
  Place *that = (Place *) o;
  return placeId_ != nil ? [placeId_ isEqual:that.placeId] : that.placeId == nil;
}

- (NSUInteger)hashOfObject {
  return placeId_ != nil ? [placeId_ hash] : 0;
}

- (BOOL)isEqual:(id)o {
  return (self == o || o != nil) && [self class] == [o class] && [self isEqualsToWithIComparableObject:(id<IComparableObject>) o];
}

- (NSUInteger)hash {
  return [self hashOfObject];
}

+ (void)initialize {
  if (self == [Place class]) {
    {
      Place_CLASS_NAME_ = NSStringFromClass([Place class]);
    }
  }
}

- (void)copyAllPropertiesTo:(id)copy {
  
  Place *typedCopy = (Place *) copy;
  typedCopy.CRUDOperation = CRUDOperation_;
  typedCopy.placeId = placeId_;
  typedCopy.name = name_;
  typedCopy.address = address_;
  typedCopy.latLng = latLng_;
  typedCopy.categoryId = categoryId_;
  typedCopy.category = category_;
  typedCopy.websiteUrl = websiteUrl_;
  typedCopy.imageUrl = imageUrl_;
  typedCopy.distanceToInterest = distanceToInterest_;
  typedCopy.rating = rating_;
  typedCopy.isFavorite = isFavorite_;
  typedCopy.showWebsite = showWebsite_;
}

@end
