//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/domain/PlaceModifiedEvent.java
//
//

@class Place;

#import <jVanila/jvanila.h>


@interface PlaceModifiedEvent : DataObject {
 @public
  Place *place_;
}

@property (nonatomic, strong) Place *place;

+ (NSString *)CLASS_NAME;
- (id)initWithPlace:(Place *)place;
@end

typedef PlaceModifiedEvent ComHomeawayHomeawayplacesDomainPlaceModifiedEvent;
