//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/domain/Place.java
//
//



#import <jVanila/jvanila.h>



@interface Place : DataObject < IComparableObject > {
 @public
  NSString *CRUDOperation_;
  NSString *placeId_;
  NSString *name_;
  NSString *address_;
  VanilaLocation *latLng_;
  NSString *categoryId_;
  NSString *category_;
  NSString *websiteUrl_;
  NSString *imageUrl_;
  int distanceToInterest_;
  float rating_;
  BOOL isFavorite_;
  BOOL showWebsite_;
}

@property (nonatomic, copy) NSString *CRUDOperation;
@property (nonatomic, copy) NSString *placeId;
@property (nonatomic, copy) NSString *name;
@property (nonatomic, copy) NSString *address;
@property (nonatomic, strong) VanilaLocation *latLng;
@property (nonatomic, copy) NSString *categoryId;
@property (nonatomic, copy) NSString *category;
@property (nonatomic, copy) NSString *websiteUrl;
@property (nonatomic, copy) NSString *imageUrl;
@property (nonatomic, assign) int distanceToInterest;
@property (nonatomic, assign) float rating;
@property (nonatomic, assign) BOOL isFavorite;
@property (nonatomic, assign) BOOL showWebsite;

+ (NSString *)CLASS_NAME;
- (id)init;
- (BOOL)isEqualsToWithIComparableObject:(id<IComparableObject>)o;
- (NSUInteger)hashOfObject;
- (BOOL)isEqual:(id)o;
- (NSUInteger)hash;
@end

typedef Place ComHomeawayHomeawayplacesDomainPlace;
