//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/domain/PlacesProvider.java
//
//

@class AsyncToken;

@class Place;
@class PlacesContext;
@class PlacesProvider_SearchOptions;






@protocol PlacesProvider_Callback;

#import <jVanila/jvanila.h>


@interface PlacesProvider : VanilaObject {
 @public
  id<IMobilePlatformFactory> mMobilePlatformFactory_;
  id<IEventBus> mEventBus_;
  id<IGenericList> mCallbackList_;
  id<IGenericMap> mRecentSearchResultsMap_;
  id<IGenericList> mOldestSearchPhraseList_;
}

@property (nonatomic, strong) id<IMobilePlatformFactory> mMobilePlatformFactory;
@property (nonatomic, strong) id<IEventBus> mEventBus;
@property (nonatomic, strong) id<IGenericList> mCallbackList;
@property (nonatomic, strong) id<IGenericMap> mRecentSearchResultsMap;
@property (nonatomic, strong) id<IGenericList> mOldestSearchPhraseList;

- (id)init;
- (PlacesContext *)getContext;
- (void)addCallbackWithPlacesProvider_Callback:(id<PlacesProvider_Callback>)callback;
- (void)removeCallbackWithPlacesProvider_Callback:(id<PlacesProvider_Callback>)callback;
- (AsyncToken *)fetchByIdAsyncWithNSString:(NSString *)id_;
- (AsyncToken *)fetchAllAsync;
- (AsyncToken *)fetchFavoritesAsync;
- (AsyncToken *)updateAsyncWithPlace:(Place *)place;
- (AsyncToken *)deleteAsyncWithPlace:(Place *)place;
- (void)searchWithNSString:(NSString *)query
withPlacesProvider_SearchOptions:(PlacesProvider_SearchOptions *)options;
- (void)searchCompleteWithNSString:(NSString *)query
withIGenericList:(id<IGenericList>)result
withFailureResponseDTO:(FailureResponseDTO *)failureResponse;
- (BOOL)isCacheHavingResultsWithNSString:(NSString *)query;
@end

typedef PlacesProvider ComHomeawayHomeawayplacesDomainPlacesProvider;

@interface PlacesProvider_SearchOptions : NSObject {
 @public
  VanilaLocation *nearbyLocation_;
  NSString *nearbyFreeFormText_;
  int radius_;
  int limit_;
  id<ILatLngBounds> withInBounds_;
}

@property (nonatomic, strong) VanilaLocation *nearbyLocation;
@property (nonatomic, copy) NSString *nearbyFreeFormText;
@property (nonatomic, assign) int radius;
@property (nonatomic, assign) int limit;
@property (nonatomic, strong) id<ILatLngBounds> withInBounds;

@end

@protocol PlacesProvider_Callback < NSObject >
- (void)onSearchCompleteWithNSString:(NSString *)query
withIGenericList:(id<IGenericList>)result
withFailureResponseDTO:(FailureResponseDTO *)failureResponse;
@end
