//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/domain/PlacesContext.java
//
//

#import "PlacesContext.h"

@implementation PlacesContext

@synthesize poi = poi_;
@synthesize fetchLimit = fetchLimit_;
@synthesize cacheLimit = cacheLimit_;

- (id)init {
  return (self = [super init]);
}

- (void)copyAllPropertiesTo:(id)copy {
  
  PlacesContext *typedCopy = (PlacesContext *) copy;
  typedCopy.poi = poi_;
  typedCopy.fetchLimit = fetchLimit_;
  typedCopy.cacheLimit = cacheLimit_;
}

@end
