//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/presenters/MapPresenter.java
//
//

@class MapPresenter_MapTransaction;
@class MarkerModel;
@class Place;



@protocol IMapView;

#import <jVanila/jvanila.h>



#define MapPresenter_DEFAULT_MAP_ZOOM_LEVEL 13.0

@interface MapPresenter : Presenter < IVanilaMapCallbacks > {
 @public
  id<ILocationApi> mLocationApi_;
  BOOL mIsMapLoading_;
  BOOL mVeryFirstLoading_;
  BOOL mMapAdjusted_;
  id<IGenericList> mMarkerModelList_;
  VanilaLocation *mCenter_;
  BOOL mWaitingToRenderModel_;
  id<IGenericList> mVisibleRegionLocations_;
  id<IGenericList> mMarkers_;
  VanilaLocation *mPendingCameraZoomUpdateLatLng_;
  BOOL mCameraOperationInProgress_;
  float mCurrentZoomLevel_;
  MapPresenter_MapTransaction *mCurrentTransaction_;
  NSString *mPoiClickMessage_;
}

@property (nonatomic, strong) id<ILocationApi> mLocationApi;
@property (nonatomic, assign) BOOL mIsMapLoading;
@property (nonatomic, assign) BOOL mVeryFirstLoading;
@property (nonatomic, assign) BOOL mMapAdjusted;
@property (nonatomic, strong) id<IGenericList> mMarkerModelList;
@property (nonatomic, strong) VanilaLocation *mCenter;
@property (nonatomic, assign) BOOL mWaitingToRenderModel;
@property (nonatomic, strong) id<IGenericList> mVisibleRegionLocations;
@property (nonatomic, strong) id<IGenericList> mMarkers;
@property (nonatomic, strong) VanilaLocation *mPendingCameraZoomUpdateLatLng;
@property (nonatomic, assign) BOOL mCameraOperationInProgress;
@property (nonatomic, assign) float mCurrentZoomLevel;
@property (nonatomic, strong) MapPresenter_MapTransaction *mCurrentTransaction;
@property (nonatomic, copy) NSString *mPoiClickMessage;

+ (int)DEFAULT_MAP_BOUNDS_PADDING;
+ (void)setDEFAULT_MAP_BOUNDS_PADDINGWithInt:(int)DEFAULT_MAP_BOUNDS_PADDING;
- (id)initWithIMapView:(id<IMapView>)view;
- (void)loadWithWithIGenericList:(id<IGenericList>)places
              withVanilaLocation:(VanilaLocation *)center;
- (void)onCreate;
- (void)onDependenciesResolved;
- (void)onMapNotAvailable;
- (void)onMapAvailable;
- (BOOL)isMapLoading;
- (void)setUpMap;
- (void)onMapLoaded;
- (void)onAnimationComplete;
- (void)onCameraMove;
- (void)onAnimationCancel;
- (void)onCameraMoveStarted;
- (void)onCameraPositionChangeWithFloat:(float)zoom;
- (void)resetMap;
- (void)showMapOrInfo;
- (void)bindDataModelWithIGenericList:(id<IGenericList>)list;
- (void)bindMarkerWithMarkerModel:(MarkerModel *)model
  withMapPresenter_MapTransaction:(MapPresenter_MapTransaction *)transaction;
- (void)fixMapBoundsWithMapPresenter_MapTransaction:(MapPresenter_MapTransaction *)transaction;
- (void)moveToWithIGenericList:(id<IGenericList>)modelLocations;
- (void)moveToWithVanilaLocation:(VanilaLocation *)latLng;
- (BOOL)fixMapToVisibleModelBoundsWithVanilaLocation:(VanilaLocation *)latLng;
- (void)onMarkerClickWithMarkerModel:(MarkerModel *)markerModel;
- (void)onMarkerInfoWindowClickWithMarkerModel:(MarkerModel *)markerModel;
- (BOOL)isPointOfInterestWithPlace:(Place *)place;
- (void)onBackPressed;
- (void)onDestroy;
@end

typedef MapPresenter ComHomeawayHomeawayplacesPresentersMapPresenter;

@interface MapPresenter_MapTransaction : NSObject {
 @public
  MapPresenter *this$0_;
  id<IGenericList> list_;
  id<IGenericList> placeMarkers_;
  id<IGenericList> visiblePlaceLocations_;
  BOOL animateCamera_;
  BOOL isProcessing_;
}

@property (nonatomic, strong) MapPresenter *this$0;
@property (nonatomic, strong) id<IGenericList> list;
@property (nonatomic, strong) id<IGenericList> placeMarkers;
@property (nonatomic, strong) id<IGenericList> visiblePlaceLocations;
@property (nonatomic, assign) BOOL animateCamera;
@property (nonatomic, assign) BOOL isProcessing;

- (id)initWithMapPresenter:(MapPresenter *)outer$1
          withIGenericList:(id<IGenericList>)list;
- (void)commit;
@end
