//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/presenters/PlaceDetailPresenter.java
//
//

@class Place;
@class StaticMapDTO;
@class StaticMapMarkerDTO;


@protocol IPlaceDetailView;

#import <jVanila/jvanila.h>


@interface PlaceDetailPresenter : Presenter {
 @public
  Place *mPlace_;
  VanilaLocation *mPoi_;
}

@property (nonatomic, strong) Place *mPlace;
@property (nonatomic, strong) VanilaLocation *mPoi;

- (id)initWithIPlaceDetailView:(id<IPlaceDetailView>)view;
- (void)loadWithWithPlace:(Place *)place
       withVanilaLocation:(VanilaLocation *)center;
- (void)onCreate;
- (void)onDependenciesResolved;
- (void)loadModel;
- (void)loadStaticMap;
- (void)fireStaticMapRequestWithInt:(int)width
                            withInt:(int)height;
- (int)resolveZoomLevelWithInt:(int)distanceToInterest;
- (StaticMapMarkerDTO *)newStaticMapMarkerWithNSString:(NSString *)color
                                                                     withDouble:(double)lat
                                                                     withDouble:(double)lng
                                                                   withNSString:(NSString *)name ;
- (void)bindModel;
- (void)onPlaceItemUrlClickWithPlace:(Place *)place;
- (void)onPlaceItemFavIconClickWithPlace:(Place *)place;
- (void)syncChangeToDatabaseWithPlace:(Place *)place;
- (void)onStaticMapResultSuccessEventWithStaticMapDTO:(StaticMapDTO *)staticMap;
- (void)subscribeToEvents;
- (void)onEventWithIEvent:(id<IEvent>)event;
- (void)unsubscribeToEvents;
- (void)onBackPressed;
- (void)onDestroy;
@end

typedef PlaceDetailPresenter ComHomeawayHomeawayplacesPresentersPlaceDetailPresenter;
