//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/foursquare/sync/FSContext.java
//
//

@class FSRequestDTO;
@class PlacesProvider_SearchOptions;





#import <jVanila/jvanila.h>
#import "PlacesContext.h"

#define FSContext_DEFAULT_CACHE_LIMIT 10
#define FSContext_DEFAULT_FETCH_LIMIT 20

@interface FSContext : PlacesContext {
 @public
  id<INumberUtils> mNumberUtils_;
  id<IStringUtils> mStringUtils_;
  NSString *mClientId_;
  NSString *mClientSecret_;
  NSString *mVersion_;
}

@property (nonatomic, strong) id<INumberUtils> mNumberUtils;
@property (nonatomic, strong) id<IStringUtils> mStringUtils;
@property (nonatomic, copy) NSString *mClientId;
@property (nonatomic, copy) NSString *mClientSecret;
@property (nonatomic, copy) NSString *mVersion;

- (id)initWithNSString:(NSString *)clientId
          withNSString:(NSString *)clientSecret
          withNSString:(NSString *)version_;
- (FSRequestDTO *)buildVenueRequestWithNSString:(NSString *)query
               withPlacesProvider_SearchOptions:(PlacesProvider_SearchOptions *)options;
- (FSRequestDTO *)buildVenueRequestWithVanilaLocation:(VanilaLocation *)nearby
                                                                                           withNSString:(NSString *)query
                                                                                                withInt:(int)limit;
- (FSRequestDTO *)buildVenueRequestWithNSString:(NSString *)nearby
                                                            withNSString:(NSString *)query
                                                                 withInt:(int)limit;
- (id<IGenericMap>)newParamsWithClientAndVersion ;
@end

typedef FSContext ComHomeawayHomeawayplacesFoursquareSyncFSContext;
