//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/foursquare/sync/FSPlacesDAOFactory.java
//
//

@class FSCategoryDAO;
@class FSLocationDAO;
@class FSVenueDAO;


#import <jVanila/jvanila.h>
#import "PlacesDAOFactory.h"

@interface FSPlacesDAOFactory : PlacesDAOFactory {
 @public
  FSVenueDAO *mFSVenueDAO_;
  FSLocationDAO *mFSLocationDAO_;
  FSCategoryDAO *mFSCategoryDAO_;
  id mLock_FSPlacesDAOFactory_;
}

@property (nonatomic, strong) FSVenueDAO *mFSVenueDAO;
@property (nonatomic, strong) FSLocationDAO *mFSLocationDAO;
@property (nonatomic, strong) FSCategoryDAO *mFSCategoryDAO;
@property (nonatomic, strong) id mLock_FSPlacesDAOFactory;

- (id)init;
- (FSVenueDAO *)getFSVenueDAO;
- (FSVenueDAO *)getFSVenueDAOInternal;
- (FSCategoryDAO *)getFSCategoryDAO;
- (FSCategoryDAO *)getFSCategoryDAOInternal;
- (FSLocationDAO *)getFSLocationDAO;
- (FSLocationDAO *)getFSLocationDAODAOInternal;
- (void)onSQLiteDatabaseOpenWithISqliteAccessor:(id<ISqliteAccessor>)sqliteAccessor;
- (BOOL)isDAOIntegrityOK;
- (void)nullify;
@end

typedef FSPlacesDAOFactory ComHomeawayHomeawayplacesFoursquareSyncFSPlacesDAOFactory;
