//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/views/IMapView.java
//
//

@class MarkerModel;
@class Place;




#import <jVanila/jvanila.h>



@protocol IMapView < IView, IVanilaMap, NSObject >
- (id<IMarker>)addNewOrCachedMarkerWithMarkerModel:(MarkerModel *)model
                                                         withIMarkerOptions:(id<IMarkerOptions>)markerOptions;
- (void)showInfoMessageWithNSString:(NSString *)message;
- (void)notifyModelRefreshComplete;
- (void)showPlaceDetailViewWithPlace:(Place *)place
                  withVanilaLocation:(VanilaLocation *)center;
- (void)showInfoWindowForWithMarkerModel:(MarkerModel *)markerModel;
- (void)showCallerView;
@end

#define ComHomeawayHomeawayplacesViewsIMapView IMapView
