//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/views/IPlaceDetailView.java
//
//


@protocol IPlaceListItemView;

#import <jVanila/jvanila.h>


@protocol IPlaceDetailView < IView, NSObject >
- (void)setTitleWithWithNSString:(NSString *)title;
- (void)setStaticMapHeightWithInt:(int)height;
- (void)setStaticMapWithNSData:(NSData *)mapRawData;
- (id<IPlaceListItemView>)getPlaceListItemView;
- (void)showBrowserViewWithNSString:(NSString *)url;
- (void)showCallerView;
- (void)showProgressWithBOOL:(BOOL)show;
@end

#define ComHomeawayHomeawayplacesViewsIPlaceDetailView IPlaceDetailView
