//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/views/IPlaceListView.java
//
//

@class Place;



#import <jVanila/jvanila.h>


@protocol IPlaceListView < IView, NSObject >
- (void)setAndShowDataModelWithIGenericList:(id<IGenericList>)placeList;
- (void)showPlaceDetailViewWithPlace:(Place *)place
                  withVanilaLocation:(VanilaLocation *)center;
- (void)showMapViewWithIGenericList:(id<IGenericList>)placeList
                 withVanilaLocation:(VanilaLocation *)center;
- (void)exitApplication;
- (void)setAndShowNoDataLabelWithNSString:(NSString *)message;
- (void)hideNoDataLabel;
- (void)hideFabIcon;
- (void)showFabIcon;
- (void)setSearchFieldHintWithNSString:(NSString *)label;
- (void)setTitleWithWithNSString:(NSString *)title;
- (void)hideListView;
- (void)showInfoMessageWithNSString:(NSString *)message;
- (void)showProgressWithBOOL:(BOOL)show;
- (void)setSearchFieldTextWithNSString:(NSString *)text;
- (void)hideVirtualKeyboard;
@end

#define ComHomeawayHomeawayplacesViewsIPlaceListView IPlaceListView
