//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/views/IPlaceListItemView.java
//
//



#import <jVanila/jvanila.h>


@protocol IPlaceListItemView < IBindableView, NSObject >
- (void)setCategoryIconWithNSString:(NSString *)iconUrl;
- (void)setPlaceLabelWithNSString:(NSString *)name;
- (void)setPlaceAddressWithNSString:(NSString *)address;
- (void)setCategoryLabelWithNSString:(NSString *)categoryLabel;
- (void)setFavoriteIconWithResource:(Resource *)resource
                                                withNSString:(NSString *)tint;
- (void)setAndShowDistanceLabelWithNSString:(NSString *)distanceLabel;
- (void)setAndShowRatingIconAndLabelWithNSString:(NSString *)ratingLabel
                                    withNSString:(NSString *)ratingColor;
- (void)hideDistanceLabel;
- (void)setAndShowWebsiteUrlWithNSString:(NSString *)websiteUrl;
- (void)hideWebsiteUrl;
- (void)hideRatingIconAndLabel;
- (void)showDivider;
- (void)hideDivider;
@end

#define ComHomeawayHomeawayplacesViewsIPlaceListItemView IPlaceListItemView
