//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/core/util/AbsoluteOrRelativeDateFormatter.java
//
//

#import "Emulation.h"

@interface AbsoluteOrRelativeDateFormatter : NSObject {
}

- (NSString *)formatWithLongInt:(long long int)millis;
@end

typedef AbsoluteOrRelativeDateFormatter ComJvanilaCoreUtilAbsoluteOrRelativeDateFormatter;
