//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/core/collection/AbstractComparator.java
//
//

@protocol ICloneableObject;
@protocol IComparableObject;

#import "Emulation.h"
#import "IComparator.h"
#import "CloneableObject.h"

@interface AbstractComparator : CloneableObject < IComparator > {
}

- (BOOL)isEqualsToWithIComparableObject:(id<IComparableObject>)object;
- (NSUInteger)hashOfObject;
- (BOOL)ascendingOrder;
- (id<ICloneableObject>)deepClone;
@end

typedef AbstractComparator ComJvanilaCoreCollectionAbstractComparator;
