//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/mvp/ApplicationController.java
//
//

@class BuildInfo;
@class ResourceState;
@protocol IApplication;
@protocol IDependenciesCallback;
@protocol IEvent;
@protocol IEventBus;
@protocol IGenericList;
@protocol ILogger;
@protocol IMobilePlatformFactory;
@protocol IResourceProvider;
@protocol IStringUtils;
@protocol IWeakReference;

#import "Emulation.h"
#import "IEventSubscriber.h"
#import "IComparableObject.h"
#import "VanilaObject.h"

@interface ApplicationController : VanilaObject < IComparableObject, IEventSubscriber > {
 @public
  NSString *TAG_;
  BOOL mDependenciesEventListeningStarts_;
  id<IWeakReference> mAppWeakRef_;
  BOOL mIsOnCreateCalled_;
  BOOL mIsDestroying_;
  id<IMobilePlatformFactory> mMobilePlatformFactory_;
  id<IResourceProvider> mResourceProvider_;
  id<IStringUtils> mStringUtils_;
  id<IEventBus> mEventBus_;
  id<ILogger> mLogger_;
  BuildInfo *mBuildInfo_;
  BOOL mForcePauseNetRequestQueue_;
  id<IGenericList> mDependencyCallbacks_;
}

@property (nonatomic, copy) NSString *TAG;
@property (nonatomic, assign) BOOL mDependenciesEventListeningStarts;
@property (nonatomic, strong) id<IWeakReference> mAppWeakRef;
@property (nonatomic, assign) BOOL mIsOnCreateCalled;
@property (nonatomic, assign) BOOL mIsDestroying;
@property (nonatomic, strong) id<IMobilePlatformFactory> mMobilePlatformFactory;
@property (nonatomic, strong) id<IResourceProvider> mResourceProvider;
@property (nonatomic, strong) id<IStringUtils> mStringUtils;
@property (nonatomic, strong) id<IEventBus> mEventBus;
@property (nonatomic, strong) id<ILogger> mLogger;
@property (nonatomic, strong) BuildInfo *mBuildInfo;
@property (nonatomic, assign) BOOL mForcePauseNetRequestQueue;
@property (nonatomic, strong) id<IGenericList> mDependencyCallbacks;

+ (NSString *)CLASS_NAME;
+ (ResourceState *)sSQLiteDatabaseAvailabilityState;
+ (void)setSSQLiteDatabaseAvailabilityStateWithResourceState:(ResourceState *)sSQLiteDatabaseAvailabilityState;
+ (ResourceState *)sSyncAdapterAvailabilityState;
+ (void)setSSyncAdapterAvailabilityStateWithResourceState:(ResourceState *)sSyncAdapterAvailabilityState;
- (id)initWithId:(id)app;
- (void)initInternal ;
- (void)onCreate;
- (void)onFactoryBroken;
- (void)loadDependencies;
- (void)onSubscribe;
- (void)addDependenciesCallbackWithIDependenciesCallback:(id<IDependenciesCallback>)callback;
- (void)onDemandCheckDependenciesWithIDependenciesCallback:(id<IDependenciesCallback>)callback;
- (void)onDependenciesNotAvailableWithBOOL:(BOOL)isSQLLoaded
                                  withBOOL:(BOOL)isSALoaded;
- (void)onSQLDatabaseNotAvailable;
- (void)onSyncAdapterNotAvailable;
- (void)onDependenciesResolving;
- (void)onDependenciesResolved;
- (BOOL)isSqlAccessorNull;
- (BOOL)isSQLDatabaseOpen;
- (BOOL)isSyncAdapterReadyToUse;
- (void)setSQLiteDatabaseAvailabilityStateWithInt:(int)state;
- (void)setSyncAdapterAvailabilityStateWithInt:(int)state;
- (BOOL)areDependenciesLoaded;
- (void)setApplicationWithId:(id)app;
- (id)getApplication;
- (NSString *)getStringWithNSString:(NSString *)resId;
- (BOOL)isInstanceOfWithClass:(Class )clazz;
- (BOOL)isEqualsToWithIComparableObject:(id<IComparableObject>)object;
- (NSUInteger)hashOfObject;
- (void)onEventWithIEvent:(id<IEvent>)event;
- (void)setForcePauseNetRequestQueueWithBOOL:(BOOL)forcePause;
- (BOOL)isDestroying;
- (void)onDestroyHandleDependencies;
- (void)onDestroyUnsubscribe;
- (void)onDestroy;
@end

typedef ApplicationController ComJvanilaMobileMvpApplicationController;
