//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/util/BinderUtil.java
//
//

@class DataObject;
@protocol IBindableViewVisitor;

#import "Emulation.h"

@interface BinderUtil : NSObject {
}

+ (void)refreshItemViewWithDataObject:(DataObject *)dataObject;
+ (void)refreshItemViewsWithDataObject:(DataObject *)dataObject;
+ (void)swapTagsInItemViewsWithDataObject:(DataObject *)source
                           withDataObject:(DataObject *)dataObject;
+ (void)refreshAllItemViewsWithDataObject:(DataObject *)dataObject;
+ (void)traverseWithDataObject:(DataObject *)dataObject
      withIBindableViewVisitor:(id<IBindableViewVisitor>)callback;
@end

typedef BinderUtil ComJvanilaMobileUtilBinderUtil;
