//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/core/util/BitUtil.java
//
//

#import "Emulation.h"

@interface BitUtil : NSObject {
}

+ (BOOL)containsInWithInt:(int)setBits
                  withInt:(int)searchBit;
+ (int)toggleInWithInt:(int)setBits
               withInt:(int)toggleBit;
@end

typedef BitUtil ComJvanilaCoreUtilBitUtil;
