//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/core/BuildInfo.java
//
//

#import "Emulation.h"
#import "VanilaObject.h"

#define BuildInfo_BUILD_TYPE_DEBUG 0
#define BuildInfo_BUILD_TYPE_RELEASE 1

@interface BuildInfo : VanilaObject {
 @public
  NSString *appVersion_;
  NSString *vcsRevisionNumber_;
  int previousAppDataVersion_;
  int currentAppDataVersion_;
  NSString *currentBuildId_;
  NSString *currentBuildName_;
  int buildType_;
}

@property (nonatomic, copy) NSString *appVersion;
@property (nonatomic, copy) NSString *vcsRevisionNumber;
@property (nonatomic, assign) int previousAppDataVersion;
@property (nonatomic, assign) int currentAppDataVersion;
@property (nonatomic, copy) NSString *currentBuildId;
@property (nonatomic, copy) NSString *currentBuildName;
@property (nonatomic, assign) int buildType;

+ (NSString *)CLASS_NAME;
+ (int)BUILD_TYPE_DEBUG;
+ (int)BUILD_TYPE_RELEASE;
- (id)init;
- (BOOL)isDebugBuild;
- (BOOL)isReleaseBuild;
- (NSString *)stringify;
@end

typedef BuildInfo ComJvanilaCoreBuildInfo;
