//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/core/datatype/CalendarConstants.java
//
//

#import "Emulation.h"

#define CalendarConstants_APRIL 3
#define CalendarConstants_AUGUST 7
#define CalendarConstants_DECEMBER 11
#define CalendarConstants_FEBRUARY 1
#define CalendarConstants_FRIDAY 6
#define CalendarConstants_JANUARY 0
#define CalendarConstants_JULY 6
#define CalendarConstants_JUNE 5
#define CalendarConstants_MARCH 2
#define CalendarConstants_MAY 4
#define CalendarConstants_MONDAY 2
#define CalendarConstants_NOVEMBER 10
#define CalendarConstants_OCTOBER 9
#define CalendarConstants_SATURDAY 7
#define CalendarConstants_SEPTEMBER 8
#define CalendarConstants_SUNDAY 1
#define CalendarConstants_THURSDAY 5
#define CalendarConstants_TUESDAY 3
#define CalendarConstants_WEDNESDAY 4

@interface CalendarConstants : NSObject {
}

+ (int)SUNDAY;
+ (int)MONDAY;
+ (int)TUESDAY;
+ (int)WEDNESDAY;
+ (int)THURSDAY;
+ (int)FRIDAY;
+ (int)SATURDAY;
+ (int)JANUARY;
+ (int)FEBRUARY;
+ (int)MARCH;
+ (int)APRIL;
+ (int)MAY;
+ (int)JUNE;
+ (int)JULY;
+ (int)AUGUST;
+ (int)SEPTEMBER;
+ (int)OCTOBER;
+ (int)NOVEMBER;
+ (int)DECEMBER;
@end

typedef CalendarConstants ComJvanilaCoreDatatypeCalendarConstants;
