//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/location/CircleParams.java
//
//

@class VanilaLocation;
@protocol IComparableObject;
@protocol IGenericList;

#import "Emulation.h"
#import "ComparableObject.h"

@interface CircleParams : ComparableObject {
 @public
  VanilaLocation *center_;
  double radius_;
  float strokeWidth_;
  NSString *strokeColor_;
  id<IGenericList> strokePattern_;
  NSString *fillColor_;
  BOOL isClickable_;
  BOOL isVisible_;
  float zIndex_;
  NSString *identifier_;
  id tag_;
}

@property (nonatomic, strong) VanilaLocation *center;
@property (nonatomic, assign) double radius;
@property (nonatomic, assign) float strokeWidth;
@property (nonatomic, copy) NSString *strokeColor;
@property (nonatomic, strong) id<IGenericList> strokePattern;
@property (nonatomic, copy) NSString *fillColor;
@property (nonatomic, assign) BOOL isClickable;
@property (nonatomic, assign) BOOL isVisible;
@property (nonatomic, assign) float zIndex;
@property (nonatomic, copy) NSString *identifier;
@property (nonatomic, strong) id tag;

- (id)init;
- (BOOL)isEqualsToWithIComparableObject:(id<IComparableObject>)o;
- (NSUInteger)hashOfObject;
@end

typedef CircleParams ComJvanilaMobileLocationCircleParams;
