//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/core/objectflavor/CloneableObject.java
//
//

@protocol IComparableObject;

#import "Emulation.h"
#import "ComparableObject.h"
#import "ICloneableObject.h"

@interface CloneableObject : ComparableObject < ICloneableObject, NSCopying > {
}

- (id<ICloneableObject>)clone;
- (id)copyWithZone:(NSZone *)zone;
@end

typedef CloneableObject ComJvanilaCoreObjectflavorCloneableObject;
