//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/core/objectflavor/ComparableObject.java
//
//

#import "Emulation.h"
#import "IComparableObject.h"
#import "VanilaObject.h"

@interface ComparableObject : VanilaObject < IComparableObject > {
}

- (BOOL)isInstanceOfWithClass:(Class )clazz;
- (BOOL)isEqual:(id)o;
- (NSUInteger)hash;
@end

typedef ComparableObject ComJvanilaCoreObjectflavorComparableObject;
