//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/imagecapture/common/CroppableImagePickerDelegateController.java
//
//


@class FailureResponseDTO;
@class FileDTO;
@class ImageCaptureRequest;
@class JsonFileDTO;
@protocol ICroppableImagePickerDelegate;
@protocol IEvent;
@protocol IMobilePlatformFactory;
@protocol IStringUtils;
@protocol IWeakReference;

#import "Emulation.h"
#import "IEventSubscriber.h"
#import "VanilaObject.h"

@interface CroppableImagePickerDelegateController : VanilaObject < IEventSubscriber > {
 @public
  id<IMobilePlatformFactory> mMobilePlatformFactory_;
  id<IWeakReference> mDelegateWeakRef_;
  id<IStringUtils> mStringUtils_;
  NSString *mBase64Image_;
  NSData *mImageBytes_;
  ImageCaptureRequest *mImageSyncRequest_;
  BOOL mIsDestroying_;
}

@property (nonatomic, strong) id<IMobilePlatformFactory> mMobilePlatformFactory;
@property (nonatomic, strong) id<IWeakReference> mDelegateWeakRef;
@property (nonatomic, strong) id<IStringUtils> mStringUtils;
@property (nonatomic, copy) NSString *mBase64Image;
@property (nonatomic, strong) NSData *mImageBytes;
@property (nonatomic, strong) ImageCaptureRequest *mImageSyncRequest;
@property (nonatomic, assign) BOOL mIsDestroying;

- (id)initWithICroppableImagePickerDelegate:(id<ICroppableImagePickerDelegate>)delegate;
- (id<ICroppableImagePickerDelegate>)getDelegate;
- (void)onPictureClickWithImageCaptureRequest:(ImageCaptureRequest *)imageSyncRequest;
- (void)onImagePickerDialogCameraIconClick;
- (void)onImagePickerDialogGalleryIconClick;
- (void)onImageCaptureCompleteWithNSData:(NSData *)imageInBytes
               withFileDTO:(FileDTO *)cameraPhoto;
- (void)syncPictureIfRequired;
- (void)onEventWithIEvent:(id<IEvent>)event;
- (void)onPictureUploadFailureWithFailureResponseDTO:(FailureResponseDTO *)failureResponseDTO;
- (void)onPictureUploadSuccessWithJsonFileDTO:(JsonFileDTO *)jsonFileDTO;
- (BOOL)onImageSyncCompleteWithNSString:(NSString *)url;
- (void)onImageRequestComplete;
- (void)subscribeToEvents;
- (void)unsubscribeToEvents;
- (void)release__;
@end

typedef CroppableImagePickerDelegateController ComJvanilaImagecaptureCommonCroppableImagePickerDelegateController;
