//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/mvp/DataBinder.java
//
//

@class IOSObjectArray;
@protocol IBindableView;
@protocol IMobilePlatformFactory;
@protocol IStringUtils;
@protocol IWeakReference;

#import "Emulation.h"

@interface DataBinder : NSObject {
 @public
  id<IWeakReference> mViewWeakRef_;
  id<IMobilePlatformFactory> mMobilePlatformFactory_;
  id<IStringUtils> mStringUtils_;
}

@property (nonatomic, strong) id<IWeakReference> mViewWeakRef;
@property (nonatomic, strong) id<IMobilePlatformFactory> mMobilePlatformFactory;
@property (nonatomic, strong) id<IStringUtils> mStringUtils;

- (id)initWithId:(id)view;
- (id)getView;
- (void)onCreate;
- (BOOL)onBindWithObjects:(id)models,... NS_REQUIRES_NIL_TERMINATION;
- (BOOL)onBindWithNSArray:(NSArray *)models;
- (NSString *)getStringWithNSString:(NSString *)stringResLabel;
- (void)onDestroy;
@end

typedef DataBinder ComJvanilaMobileMvpDataBinder;
