//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/job/FgAsyncJob.java
//
//

#import "Emulation.h"
#import "AsyncJob.h"

@interface FgAsyncJob : AsyncJob {
}

- (id)init;
- (void)finish;
@end

typedef FgAsyncJob ComJvanilaMobileJobFgAsyncJob;
