//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/sync/HttpHeaderBuilder.java
//
//

@class NetRequestDTO;
@protocol IGenericList;

#import "Emulation.h"

@interface HttpHeaderBuilder : NSObject {
 @public
  id<IGenericList> mCachedHeaders_;
  id mLock_;
}

@property (nonatomic, strong) id<IGenericList> mCachedHeaders;
@property (nonatomic, strong) id mLock;

- (void)prepareHeaders;
- (void)clearCachedHeaders;
- (void)buildWithNetRequestDTO:(NetRequestDTO *)request;
- (void)buildInternalWithNetRequestDTO:(NetRequestDTO *)request;
- (void)prepareAppSpecificHeadersWithNetRequestDTO:(NetRequestDTO *)request;
- (BOOL)isValid;
- (id<IGenericList>)getCachedHeaders;
- (BOOL)isDebugBuild;
- (id)init;
@end

typedef HttpHeaderBuilder ComJvanilaMobileSyncHttpHeaderBuilder;
