//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/diagnostics/IAppHealthMonitor.java
//
//

#import "Emulation.h"
#import "IVanilaObject.h"

@protocol IAppHealthMonitor < IVanilaObject, NSObject >
- (void)dumpAppHealthState;
@end

#define ComJvanilaMobileDiagnosticsIAppHealthMonitor IAppHealthMonitor
