//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/core/IApplication.java
//
//

@class ApplicationController;
@class HttpHeaderBuilder;
@class VanilaNotification;
@protocol IGenericMap;
@protocol INativePushRegistryCallback;
@protocol IPubSubTransceiver;
@protocol ISqliteOpenListener;
@protocol ISyncAdapter;
@protocol ISyncAdapterLoadCallback;

#import "Emulation.h"
#import "IVanilaObject.h"

@protocol IApplication < IVanilaObject, NSObject >
- (BOOL)init__ ;
- (void)loadSQLAccessor;
- (void)loadSQLAccessorSynchronouslyWithISqliteOpenListener:(id<ISqliteOpenListener>)listener;
- (void)loadSyncAdapterWithHttpHeaderBuilder:(HttpHeaderBuilder *)httpHeaderBuilder
                      withIPubSubTransceiver:(id<IPubSubTransceiver>)pushActivityListener;
- (void)loadSyncAdapterSynchronouslyWithISyncAdapterLoadCallback:(id<ISyncAdapterLoadCallback>)callback
                                           withHttpHeaderBuilder:(HttpHeaderBuilder *)httpHeaderBuilder
                                          withIPubSubTransceiver:(id<IPubSubTransceiver>)pushActivityListener;
- (void)relaunchWithBOOL:(BOOL)fromApps;
- (NSString *)getPackageName;
- (BOOL)isApplicationRunningInForeground;
- (void)postNotificationWithNSString:(NSString *)message
                        withNSString:(NSString *)optionalNativeClassToLaunch
withIGenericMap:(id<IGenericMap>)params;
- (void)postNotificationWithVanilaNotification:(VanilaNotification *)notification;
- (void)removeNotificationsIfAny;
- (void)showToastWithNSString:(NSString *)message;
- (BOOL)isInInitialization;
- (void)setIsInInitializationWithBOOL:(BOOL)init_;
- (id<IPubSubTransceiver>)newOrGetPubSubTransceiver ;
- (void)doNativePushRegisterWithINativePushRegistryCallback:(id<INativePushRegistryCallback>)nativePushRegistryCallback;
- (void)doNativePushUnregister;
- (void)onLaunchTimeDependenciesResolved;
- (void)notifySyncAdapterLoadingCompleteWithISyncAdapter:(id<ISyncAdapter>)syncAdapter;
- (ApplicationController *)getController;
@end

#define ComJvanilaMobileCoreIApplication IApplication
