//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/sync/IAsyncNetResponseListener.java
//
//

@class NetResponseDTO;

#import "Emulation.h"

@protocol IAsyncNetResponseListener < NSObject >
- (void)onNetResponseWithNetResponseDTO:(NetResponseDTO *)netResponseDTO;
@end

#define ComJvanilaMobileSyncIAsyncNetResponseListener IAsyncNetResponseListener
