//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/job/IAsyncTokenResultCallback.java
//
//

@class AsyncToken;

#import "Emulation.h"

@protocol IAsyncTokenResultCallback < NSObject >
- (void)onTokenResultWithAsyncToken:(AsyncToken *)token
                                                      withId:(id)result;
@end

#define ComJvanilaMobileJobIAsyncTokenResultCallback IAsyncTokenResultCallback
