//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/mvp/IBindableView.java
//
//

@class DataBinder;

#import "Emulation.h"
#import "IVanilaObject.h"

@protocol IBindableView < IVanilaObject, NSObject >
- (void)showView;
- (void)hideView;
- (void)setTagWithId:(id)tag;
- (void)addTagWithId:(id)tag;
- (id)getTag;
- (DataBinder *)getDataBinder;
- (void)refresh;
@end

#define ComJvanilaMobileMvpIBindableView IBindableView
