//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/location/IButtCap.java
//
//

#import "Emulation.h"
#import "ICap.h"

@protocol IButtCap < ICap, NSObject >
@end

#define ComJvanilaMobileLocationIButtCap IButtCap
