//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/core/datatype/ICalendar.java
//
//

@protocol IDateTime;
@protocol ITimeZone;

#import "Emulation.h"
#import "ICloneableObject.h"

@protocol ICalendar < ICloneableObject, NSObject >
- (id<ICalendar>)setDateTimeWithIDateTime:(id<IDateTime>)dateTime;
- (id<IDateTime>)getDateTime;
- (id<ICalendar>)setDateTimeMillisWithLongInt:(long long int)dateTime;
- (long long int)getDateTimeMillis;
- (id<ICalendar>)setTimeZoneWithITimeZone:(id<ITimeZone>)timeZone;
- (id<ITimeZone>)getTimeZone;
- (id<ICalendar>)setHoursIn24HrFormatWithInt:(int)hours;
- (id<ICalendar>)setDateTimeLabelWithPatternWithNSString:(NSString *)dateTimeLabel
                                                                     withNSString:(NSString *)pattern;
- (NSString *)getDateTimeLabelWithNSString:(NSString *)pattern;
- (id<ICalendar>)setMinutesWithInt:(int)minutes;
- (int)getMinsOfTheDay;
- (id<ICalendar>)setSecondsWithInt:(int)seconds;
- (int)getSecondsOfTheDay;
- (id<IDateTime>)getDateWithOutTime;
- (int)getDayOfWeek;
- (id<IDateTime>)getStartDateTimeOfWeek;
- (id<IDateTime>)getEndDateTimeOfWeek;
- (id<ICalendar>)setMonthWithInt:(int)month;
- (int)getMonth;
- (id<ICalendar>)setDayOfMonthWithInt:(int)date;
- (int)getDayOfMonth;
- (int)getTotalDaysInMonth;
- (id<ICalendar>)addDaysOfMonthWithInt:(int)noOfDaysOfMonth;
- (id<IDateTime>)getStartDateTimeOfMonth;
- (id<ICalendar>)setYearWithInt:(int)year;
- (int)getYear;
- (int)getDayOfYear;
- (int)getWeekOfYear;
- (int)getMaximumSupportedYear;
- (id<ICalendar>)addDaysOfYearWithInt:(int)noOfDaysOfYear;
- (id<ICalendar>)addMonthsOfYearWithInt:(int)noOfMonths;
@end

#define ComJvanilaCoreDatatypeICalendar ICalendar
