//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/location/ICap.java
//
//

#import "Emulation.h"
#import "IVanilaObject.h"

@protocol ICap < IVanilaObject, NSObject >
@end

#define ComJvanilaMobileLocationICap ICap
