//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/location/ICircleOptions.java
//
//

@class CircleParams;

#import "Emulation.h"

@protocol ICircleOptions < NSObject >
- (CircleParams *)getParams;
- (void)build;
@end

#define ComJvanilaMobileLocationICircleOptions ICircleOptions
