//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/location/ICircle.java
//
//

@class CircleParams;

#import "Emulation.h"

@protocol ICircle < NSObject >
- (void)setTagWithId:(id)tag;
- (id)getTag;
- (void)setVisibleWithBOOL:(BOOL)visible;
- (CircleParams *)getCircleParams;
- (void)remove;
@end

#define ComJvanilaMobileLocationICircle ICircle
