//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/core/objectflavor/ICloneableObject.java
//
//

#import "Emulation.h"
#import "IComparableObject.h"

@protocol ICloneableObject < IComparableObject, NSObject >
- (id<ICloneableObject>)deepClone;
@end

#define ComJvanilaCoreObjectflavorICloneableObject ICloneableObject
