//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/core/objectflavor/IComparableObject.java
//
//

#import "Emulation.h"
#import "IVanilaObject.h"

@protocol IComparableObject < IVanilaObject, NSObject >
- (BOOL)isEqualsToWithIComparableObject:(id<IComparableObject>)object;
- (NSUInteger)hashOfObject;
- (BOOL)isInstanceOfWithClass:(Class )clazz;
@end

#define ComJvanilaCoreObjectflavorIComparableObject IComparableObject
