//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/core/collection/IComparator.java
//
//

#import "Emulation.h"
#import "ICloneableObject.h"

@protocol IComparator < ICloneableObject, NSObject >
- (BOOL)ascendingOrder;
- (int)compareWithId:(id)x
              withId:(id)y;
@end

#define ComJvanilaCoreCollectionIComparator IComparator
