//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/core/collection/IComparable.java
//
//

#import "Emulation.h"


@protocol IComparable < NSObject >
- (int)compareToWithId:(id)o;
@end

#define ComJvanilaCoreCollectionIComparable IComparable
