//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/imagecapture/common/ICroppableImagePickerCallback.java
//
//


@class FileDTO;

#import "Emulation.h"

@protocol ICroppableImagePickerCallback < NSObject >
- (void)onImageCaptureCompleteWithNSData:(NSData *)imageInBytes
               withFileDTO:(FileDTO *)file;
@end

#define ComJvanilaImagecaptureCommonICroppableImagePickerCallback ICroppableImagePickerCallback
