//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/imagecapture/common/ICroppableImagePickerDelegate.java
//
//


@class ImageCaptureRequest;

#import "Emulation.h"

@protocol ICroppableImagePickerDelegate < NSObject >
- (void)dispatchOnPictureClickWithImageCaptureRequest:(ImageCaptureRequest *)imageSyncRequest;
- (void)showImagePickerDialog;
- (void)showCameraViewWithBOOL:(BOOL)deleteFileAfterCapture
                  withNSString:(NSString *)outputPath
                       withInt:(int)quality;
- (void)showGalleryViewWithNSString:(NSString *)outputPath
                            withInt:(int)quality;
- (void)setPictureWithNSData:(NSData *)stream;
- (void)showImageChangeProgressWithNSString:(NSString *)status;
- (void)updateLocalImageWithNSString:(NSString *)url
               withNSData:(NSData *)picture_bytes;
- (void)release__;
@end

#define ComJvanilaImagecaptureCommonICroppableImagePickerDelegate ICroppableImagePickerDelegate
