//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/location/ICustomCap.java
//
//

#import "Emulation.h"
#import "ICap.h"

@protocol ICustomCap < ICap, NSObject >
- (void)setIconWithId:(id)nativeBitmapDescriptor;
- (void)setRefWidthWithFloat:(float)refWidth;
- (void)build;
@end

#define ComJvanilaMobileLocationICustomCap ICustomCap
