//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/storage/IDAOFactory.java
//
//

@class LookUpDAO;
@protocol ISyncStatsDAO;

#import "Emulation.h"
#import "IVanilaObject.h"
#import "ISqliteOpenListener.h"

@protocol IDAOFactory < IVanilaObject, ISqliteOpenListener, NSObject >
- (LookUpDAO *)getLookUpDAOWithNSString:(NSString *)classOfT
                                                    withNSString:(NSString *)optionalFileName;
- (id<ISyncStatsDAO>)getSyncStatsDAO;
- (BOOL)isDAOIntegrityOK;
- (void)reset;
@end

#define ComJvanilaMobileStorageIDAOFactory IDAOFactory
