//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/location/IDash.java
//
//

#import "Emulation.h"
#import "IPatternItem.h"

@protocol IDash < IPatternItem, NSObject >
- (void)setLengthWithFloat:(float)length;
- (float)getLength;
@end

#define ComJvanilaMobileLocationIDash IDash
