//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/core/IDateTimeUtils.java
//
//

#import "Emulation.h"
#import "IVanilaObject.h"

@protocol IDateTimeUtils < IVanilaObject, NSObject >
- (NSString *)getRelativeTimeSpanWithLongInt:(long long int)then
                                 withLongInt:(long long int)now;
- (NSString *)getRelativeTimeSpanStringWithLongInt:(long long int)millis
                                          withBOOL:(BOOL)withPreposition;
- (NSString *)getRelativeTimeSpanStringWithLongInt:(long long int)time
                                       withLongInt:(long long int)now
                                       withLongInt:(long long int)minResolution
                                           withInt:(int)flags;
@end

#define ComJvanilaCoreIDateTimeUtils IDateTimeUtils
