//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/mvp/IDependenciesCallback.java
//
//

#import "Emulation.h"
#import "IEventSubscriber.h"

@protocol IDependenciesCallback < IEventSubscriber, NSObject >
- (void)onDependenciesResolving;
- (void)onDependenciesResolved;
- (void)onDependenciesResolvingFailed;
@end

#define ComJvanilaMobileMvpIDependenciesCallback IDependenciesCallback
