//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/location/IDot.java
//
//

#import "Emulation.h"
#import "IPatternItem.h"

@protocol IDot < IPatternItem, NSObject >
@end

#define ComJvanilaMobileLocationIDot IDot
