//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/core/eventbus/IEventBus.java
//
//

@protocol IEvent;
@protocol IEventSubscriber;

#import "Emulation.h"

@protocol IEventBus < NSObject >
- (void)subscribeWithNSString:(NSString *)eventClassName
withIEventSubscriber:(id<IEventSubscriber>)eventSubscriber;
- (void)unsubscribeWithNSString:(NSString *)eventClassName
withIEventSubscriber:(id<IEventSubscriber>)eventSubscriber;
- (void)unsubscribeAllEventsOfWithIEventSubscriber:(id<IEventSubscriber>)eventSubscriber;
- (void)publishWithIEvent:(id<IEvent>)event;
- (void)flushBus;
@end

#define ComJvanilaCoreEventbusIEventBus IEventBus
