//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/core/eventbus/IEvent.java
//
//

#import "Emulation.h"
#import "IComparableObject.h"

@protocol IEvent < IComparableObject, NSObject >
@end

#define ComJvanilaCoreEventbusIEvent IEvent
