//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/core/eventbus/IEventSubscriber.java
//
//

@protocol IEvent;

#import "Emulation.h"
#import "IVanilaObject.h"

@protocol IEventSubscriber < IVanilaObject, NSObject >
- (void)onEventWithIEvent:(id<IEvent>)event;
@end

#define ComJvanilaCoreEventbusIEventSubscriber IEventSubscriber
