//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/mvp/IFragmentView.java
//
//

#import "Emulation.h"
#import "IView.h"

@protocol IFragmentView < IView, NSObject >
- (id<IView>)getParentView;
@end

#define ComJvanilaMobileMvpIFragmentView IFragmentView
