//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/location/IGap.java
//
//

#import "Emulation.h"
#import "IPatternItem.h"

@protocol IGap < IPatternItem, NSObject >
- (void)setLengthWithFloat:(float)length;
- (float)getLength;
@end

#define ComJvanilaMobileLocationIGap IGap
