//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/core/collection/IGenericMap.java
//
//

@class MapBehaviorType;
@protocol IGenericList;

#import "Emulation.h"
#import "ICloneableObject.h"

@protocol IGenericMap < ICloneableObject, NSObject >
- (void)putWithId:(id)key
           withId:(id)value;
- (void)putAllWithIGenericMap:(id<IGenericMap>)map;
- (id<IGenericList>)entrySet;
- (void)removeWithId:(id)key;
- (id)getWithId:(id)key;
- (BOOL)containsKeyWithId:(id)key;
- (BOOL)containsValueWithId:(id)value;
- (void)clear;
- (int)size;
- (id<IGenericList>)getKeys;
- (id<IGenericList>)getValues;
- (MapBehaviorType *)getMapBehaviorType;
@end

#define ComJvanilaCoreCollectionIGenericMap IGenericMap
