//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/core/collection/IGenericList.java
//
//

@class ListBehaviorType;
@protocol IComparator;
@protocol IPredicate;

#import "Emulation.h"
#import "ICloneableObject.h"


@protocol IGenericList < ICloneableObject, NSFastEnumeration, NSObject >
- (void)addWithId:(id)item;
- (void)addWithInt:(int)index
            withId:(id)item;
- (void)addAllWithIGenericList:(id<IGenericList>)list;
- (BOOL)removeWithId:(id)item;
- (id)getWithInt:(int)index;
- (int)indexOfWithId:(id)Item;
- (id)removeWithInt:(int)index;
- (void)replaceWithId:(id)obj
              withInt:(int)atIndex;
- (void)insertWithId:(id)obj
             withInt:(int)atIndex;
- (void)clear;
- (BOOL)isEmpty;
- (BOOL)containsWithId:(id)obj;
- (int)size;
- (ListBehaviorType *)getListBehaviorType;
- (void)sortByNaturalOrder;
- (void)sortByNaturalOrderWithBOOL:(BOOL)ascending;
- (void)sortByNaturalOrderWithNSString:(NSString *)property;
- (void)sortByWithIComparator:(id<IComparator>)comparator;
- (id<IGenericList>)filterByWithIPredicate:(id<IPredicate>)predicate;
- (void)removeByWithIPredicate:(id<IPredicate>)predicate;
@end

#define ComJvanilaCoreCollectionIGenericList IGenericList
