//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/job/IJobHandler.java
//
//

@protocol IAsyncJob;

#import "Emulation.h"
#import "IVanilaObject.h"

@protocol IJobHandler < IVanilaObject, NSObject >
- (void)doCancelledJobWithId:(id)job;
- (void)doJobWithId:(id)job;
- (void)cancelJobsByFamilyWithNSString:(NSString *)tag;
- (void)cancelJobWithId:(id)job;
- (void)doQuit;
@end

#define ComJvanilaMobileJobIJobHandler IJobHandler
