//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/core/datatype/IJsonObject.java
//
//

@protocol IJsonArray;

#import "Emulation.h"
#import "ICloneableObject.h"

@protocol IJsonObject < ICloneableObject, NSObject >
- (void)putWithNSString:(NSString *)key
           withNSString:(NSString *)value;
- (void)putWithNSString:(NSString *)key
               withBOOL:(BOOL)value;
- (void)putWithNSString:(NSString *)key
            withUnichar:(char)value;
- (void)putWithNSString:(NSString *)key
                withInt:(int)value;
- (void)putWithNSString:(NSString *)key
            withLongInt:(long long int)value;
- (void)putWithNSString:(NSString *)key
              withFloat:(float)value;
- (void)putWithNSString:(NSString *)key
             withDouble:(double)value;
- (void)putWithNSString:(NSString *)key
withIJsonObject:(id<IJsonObject>)value;
- (void)putWithNSString:(NSString *)key
withIJsonArray:(id<IJsonArray>)jsonArray;
@end

#define ComJvanilaCoreDatatypeIJsonObject IJsonObject
