//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/core/datatype/IJsonArray.java
//
//

@protocol IJsonObject;

#import "Emulation.h"
#import "ICloneableObject.h"

@protocol IJsonArray < ICloneableObject, NSObject >
- (void)putWithNSString:(NSString *)obj;
- (void)putWithBOOL:(BOOL)value;
- (void)putWithUnichar:(char)value;
- (void)putWithInt:(int)value;
- (void)putWithLongInt:(long long int)value;
- (void)putWithFloat:(float)value;
- (void)putWithDouble:(double)value;
- (void)putWithIJsonObject:(id<IJsonObject>)jsonObject;
- (void)putWithIJsonArray:(id<IJsonArray>)jsonArray;
- (int)size;
@end

#define ComJvanilaCoreDatatypeIJsonArray IJsonArray
