//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/location/ILatLngBounds.java
//
//

@class VanilaLocation;
@protocol IGenericList;

#import "Emulation.h"

@protocol ILatLngBounds < NSObject >
- (void)includeWithVanilaLocation:(VanilaLocation *)latlng;
- (void)includeAllWithIGenericList:(id<IGenericList>)latlngs;
- (void)build;
- (VanilaLocation *)getCenter;
- (VanilaLocation *)getNorthEast;
- (VanilaLocation *)getSouthWest;
@end

#define ComJvanilaMobileLocationILatLngBounds ILatLngBounds
