//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/location/ILocationApi.java
//
//

@class CircleParams;
@class MarkerParams;
@class PolygonParams;
@class PolylineParams;
@class VanilaLocation;
@protocol IButtCap;
@protocol ICircleOptions;
@protocol ICustomCap;
@protocol IDash;
@protocol IDot;
@protocol IGap;
@protocol IGenericList;
@protocol ILatLngBounds;
@protocol IMarkerOptions;
@protocol IPolygon;
@protocol IPolygonOptions;
@protocol IPolylineOptions;
@protocol IRoundCap;
@protocol ISquareCap;

#import "Emulation.h"
#import "IVanilaObject.h"

@protocol ILocationApi < IVanilaObject, NSObject >
- (id<IPolygon>)newPolygonWithIGenericList:(id<IGenericList>)locations ;
- (double)distanceBetweenWithDouble:(double)lat1
                         withDouble:(double)long1
                         withDouble:(double)lat2
                         withDouble:(double)long2;
- (double)distanceBetweenWithVanilaLocation:(VanilaLocation *)previousLocation
                         withVanilaLocation:(VanilaLocation *)stopLocation;
- (id<ILatLngBounds>)newLatLngBounds ;
- (id<IMarkerOptions>)newMarkerOptionsWithMarkerParams:(MarkerParams *)markerParams ;
- (id<IPolylineOptions>)newPolylineOptionsWithPolylineParams:(PolylineParams *)polylineParams ;
- (id<IPolygonOptions>)newPolygonOptionsWithPolygonParams:(PolygonParams *)polylineParams ;
- (id<ICircleOptions>)newCircleOptionsWithCircleParams:(CircleParams *)circleParams ;
- (id<IDot>)newDot ;
- (id<IDash>)newDashWithFloat:(float)length ;
- (id<IGap>)newGapWithFloat:(float)length ;
- (id<IButtCap>)newButtCap ;
- (id<ISquareCap>)newSquareCap ;
- (id<IRoundCap>)newRoundCap ;
- (id<ICustomCap>)newCustomCapWithId:(id)nativeBitmapDescriptior
                                                    withFloat:(float)refWidth ;
@end

#define ComJvanilaMobileLocationILocationApi ILocationApi
