//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/core/locale/ILocale.java
//
//

#import "Emulation.h"
#import "IComparableObject.h"

@protocol ILocale < IComparableObject, NSObject >
- (NSString *)getLocaleLabel;
@end

#define ComJvanilaCoreLocaleILocale ILocale
