//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/core/util/ILogger.java
//
//

@class IOSObjectArray;

#import "Emulation.h"
#import "IVanilaObject.h"

@protocol ILogger < IVanilaObject, NSObject >
- (void)setKeepQuietWithBOOL:(BOOL)quiet;
- (void)printWithNSString:(NSString *)message;
- (void)logWithNSString:(NSString *)tag
           withNSString:(NSString *)message;
- (void)logfWithNSString:(NSString *)tag
            withNSString:(NSString *)message
       , ... NS_REQUIRES_NIL_TERMINATION;
@end

#define ComJvanilaCoreUtilILogger ILogger
