//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/imagecapture/common/ImageCaptureRequest.java
//
//


@protocol ICroppableImagePickerCallback;

#import "Emulation.h"
#import "DataObject.h"

#define ImageCaptureRequest_serialVersionUID 1

@interface ImageCaptureRequest : DataObject {
 @public
  NSString *entityType_;
  NSString *entityUuid_;
  NSString *pictureEndPoint_;
  NSString *beforeSyncPictureUrlIfAny_;
  NSString *postSyncPictureUrl_;
  NSData *syncedImageBytes_;
  BOOL showOnlyCamera_;
  BOOL showOnlyGallery_;
  BOOL syncToServer_;
  BOOL deleteFileAfterCapture_;
  BOOL bindToView_;
  int quality_;
  NSString *outputPath_;
  id<ICroppableImagePickerCallback> callback_;
}

@property (nonatomic, copy) NSString *entityType;
@property (nonatomic, copy) NSString *entityUuid;
@property (nonatomic, copy) NSString *pictureEndPoint;
@property (nonatomic, copy) NSString *beforeSyncPictureUrlIfAny;
@property (nonatomic, copy) NSString *postSyncPictureUrl;
@property (nonatomic, strong) NSData *syncedImageBytes;
@property (nonatomic, assign) BOOL showOnlyCamera;
@property (nonatomic, assign) BOOL showOnlyGallery;
@property (nonatomic, assign) BOOL syncToServer;
@property (nonatomic, assign) BOOL deleteFileAfterCapture;
@property (nonatomic, assign) BOOL bindToView;
@property (nonatomic, assign) int quality;
@property (nonatomic, copy) NSString *outputPath;
@property (nonatomic, strong) id<ICroppableImagePickerCallback> callback;

+ (NSString *)TAG;
+ (NSString *)CLASS_NAME;
@end

typedef ImageCaptureRequest ComJvanilaImagecaptureCommonImageCaptureRequest;
