//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/core/collection/IMapEntity.java
//
//

#import "Emulation.h"
#import "ICloneableObject.h"

@protocol IMapEntity < ICloneableObject, NSObject >
- (id)getKey;
- (id)getValue;
@end

#define ComJvanilaCoreCollectionIMapEntity IMapEntity
