//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/location/IMarkerOptions.java
//
//

@class MarkerParams;

#import "Emulation.h"

@protocol IMarkerOptions < NSObject >
- (MarkerParams *)getParams;
- (void)build;
@end

#define ComJvanilaMobileLocationIMarkerOptions IMarkerOptions
