//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/location/IMarker.java
//
//

@class MarkerParams;
@class VanilaLocation;

#import "Emulation.h"
#import "IComparableObject.h"

@protocol IMarker < IComparableObject, NSObject >
- (VanilaLocation *)getPosition;
- (void)setTagWithId:(id)tag;
- (id)getTag;
- (void)remove;
- (void)setRotationWithFloat:(float)degrees;
- (void)setVisibleWithBOOL:(BOOL)visible;
- (MarkerParams *)getMarkerParams;
@end

#define ComJvanilaMobileLocationIMarker IMarker
