//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/IMobilePlatformFactory.java
//
//

@protocol IAppHealthMonitor;
@protocol IApplication;
@protocol IDAOFactory;
@protocol IImageFetcher;
@protocol ILocationApi;
@protocol ISqliteAccessor;
@protocol ISyncAdapter;

#import "Emulation.h"
#import "IPlatformFactory.h"

@protocol IMobilePlatformFactory < IPlatformFactory, NSObject >
- (void)setApplicationWithIApplication:(id<IApplication>)application;
- (id<IApplication>)getApplication;
- (void)setDAOFactoryWithId:(id)daoFactory;
- (id)getDAOFactory;
- (void)setSyncAdapterWithISyncAdapter:(id<ISyncAdapter>)syncAdapter;
- (id<ISyncAdapter>)getSyncAdapter;
- (void)setSqliteAccessorWithISqliteAccessor:(id<ISqliteAccessor>)sqliteAccessor;
- (id<ISqliteAccessor>)getSqliteAccessor;
- (id<IAppHealthMonitor>)getAppHealthMonitor;
- (id<ILocationApi>)getLocationApi;
- (id<IImageFetcher>)getImageFetcher;
- (void)setReadyWithBOOL:(BOOL)isReady;
- (BOOL)isReady;
@end

#define ComJvanilaMobileIMobilePlatformFactory IMobilePlatformFactory
