//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/sync/IMqttInQueue.java
//
//

@class MqttMessageDTO;

#import "Emulation.h"
#import "IVanilaObject.h"

@protocol IMqttInQueue < IVanilaObject, NSObject >
- (void)onProcessingCompleteWithMqttMessageDTO:(MqttMessageDTO *)mqttMessageDTO;
@end

#define ComJvanilaMobileSyncIMqttInQueue IMqttInQueue
