//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/core/INativePushRegistryCallback.java
//
//

#import "Emulation.h"
#import "IVanilaObject.h"

@protocol INativePushRegistryCallback < IVanilaObject, NSObject >
- (void)onDevicePushRegistrationCompleteWithNSString:(NSString *)registrationId;
@end

#define ComJvanilaMobileCoreINativePushRegistryCallback INativePushRegistryCallback
