//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/job/IOAsyncJob.java
//
//

#import "Emulation.h"
#import "BgAsyncJob.h"

@interface IOAsyncJob : BgAsyncJob {
}

- (id)init;
- (void)finish;
@end

typedef IOAsyncJob ComJvanilaMobileJobIOAsyncJob;
