//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/location/IPatternItem.java
//
//

#import "Emulation.h"
#import "IVanilaObject.h"

@protocol IPatternItem < IVanilaObject, NSObject >
@end

#define ComJvanilaMobileLocationIPatternItem IPatternItem
