//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/core/IPermissionChecker.java
//
//

#import "Emulation.h"
#import "IVanilaObject.h"

@protocol IPermissionChecker < IVanilaObject, NSObject >
@end

#define ComJvanilaMobileCoreIPermissionChecker IPermissionChecker
