//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/sync/IPeriodicPollingPool.java
//
//

@class NetRequestDTO;
@protocol IPollingRequestHost;

#import "Emulation.h"
#import "IVanilaObject.h"

@protocol IPeriodicPollingPool < IVanilaObject, NSObject >
- (void)startPolling;
- (void)stopPolling;
- (void)addToPoolWithNetRequestDTO:(NetRequestDTO *)netRequest
           withIPollingRequestHost:(id<IPollingRequestHost>)pollingRequestHost;
- (void)removeFromPoolWithNetRequestDTO:(NetRequestDTO *)netRequest;
- (void)clearPool;
@end

#define ComJvanilaMobileSyncIPeriodicPollingPool IPeriodicPollingPool
