//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/core/IPlatformFactory.java
//
//

@class IOSObjectArray;
@class BuildInfo;
@class ListBehaviorType;
@class MapBehaviorType;
@class PlatformInfo;
@protocol ICalendar;
@protocol IDateTime;
@protocol IDateTimeUtils;
@protocol IEventBus;
@protocol IFileAccessor;
@protocol IGenericList;
@protocol IGenericMap;
@protocol IJsonArray;
@protocol IJsonObject;
@protocol ILogger;
@protocol INumberUtils;
@protocol IResourceProvider;
@protocol ISpannableStringBuilder;
@protocol IStringBuilder;
@protocol IStringUtils;
@protocol ISynchronizedList;
@protocol ITimeZone;
@protocol IUUIDGenerator;
@protocol IWeakReference;

#import "Emulation.h"

@protocol IPlatformFactory < NSObject >
- (BOOL)isObjectOfTypeWithId:(id)t
                withClass:(Class )objectClass;
- (NSMutableArray *)newArrayWithInt:(int)size
                                  withId:(id)defaultValue ;
- (id<IGenericList>)newList ;
- (id<IGenericList>)newListWithWithListBehaviorType:(ListBehaviorType *)listBehaviorType ;
- (id<ISynchronizedList>)newSynchronizedListWithIGenericList:(id<IGenericList>)list ;
- (id<IGenericMap>)newMap ;
- (id<IGenericMap>)newMapWithWithMapBehaviorType:(MapBehaviorType *)mapBehaviorType ;
- (id<IWeakReference>)newWeakReferenceWithId:(id)t ;
- (id<INumberUtils>)getNumberUtils;
- (id<IStringUtils>)getStringUtils;
- (id<IDateTimeUtils>)getDateTimeUtils;
- (id<IStringBuilder>)newStringBuilder ;
- (id<ISpannableStringBuilder>)newSpannableStringBuilder ;
- (id<IDateTime>)newDateTime ;
- (id<IDateTime>)newDateTimeWithLongInt:(long long int)dateTimeInMillis ;
- (id<IDateTime>)newDateTimeWithNSString:(NSString *)dateTimeString
                                                     withNSString:(NSString *)pattern
                           withITimeZone:(id<ITimeZone>)timeZone ;
- (id<ITimeZone>)newTimeZoneWithNSString:(NSString *)olsonIdOrGmtOffset
                                                          withInt:(int)timeZoneOffsetInMinutes ;
- (id<ICalendar>)newCalendarWithIDateTime:(id<IDateTime>)dateTime
                                                     withITimeZone:(id<ITimeZone>)timeZone ;
- (id<IJsonObject>)newJsonObjectWithNSString:(NSString *)json ;
- (id<IJsonArray>)newJsonArrayWithNSString:(NSString *)json ;
- (id<IUUIDGenerator>)getUUIDGenerator;
- (id<ILogger>)getLogger;
- (id<IResourceProvider>)getResourceProvider;
- (id<IEventBus>)getEventBus;
- (id<IFileAccessor>)getFileAccessor;
- (PlatformInfo *)getPlatformInfo;
- (BuildInfo *)getBuildInfo;
@end

#define ComJvanilaCoreIPlatformFactory IPlatformFactory
