//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/location/IPolyline.java
//
//

@class PolylineParams;

#import "Emulation.h"

@protocol IPolyline < NSObject >
- (void)setTagWithId:(id)tag;
- (id)getTag;
- (PolylineParams *)getPolylineParams;
- (void)remove;
- (void)setVisibleWithBOOL:(BOOL)visible;
@end

#define ComJvanilaMobileLocationIPolyline IPolyline
