//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/location/IPolylineOptions.java
//
//

@class PolylineParams;

#import "Emulation.h"

@protocol IPolylineOptions < NSObject >
- (PolylineParams *)getParams;
- (void)build;
@end

#define ComJvanilaMobileLocationIPolylineOptions IPolylineOptions
