//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/location/IPolygonOptions.java
//
//

@class PolygonParams;

#import "Emulation.h"

@protocol IPolygonOptions < NSObject >
- (PolygonParams *)getParams;
- (void)build;
@end

#define ComJvanilaMobileLocationIPolygonOptions IPolygonOptions
