//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/location/IPolygon.java
//
//

@class PolygonParams;
@class VanilaLocation;
@protocol IGenericList;

#import "Emulation.h"

@protocol IPolygon < NSObject >
- (PolygonParams *)getPolygonParams;
- (void)setTagWithId:(id)tag;
- (id)getTag;
- (void)remove;
- (void)setVisibleWithBOOL:(BOOL)visible;
- (id<IGenericList>)getLocations;
- (BOOL)isContainsWithVanilaLocation:(VanilaLocation *)vanilaLocation;
@end

#define ComJvanilaMobileLocationIPolygon IPolygon
