//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/sync/IPollingRequestHost.java
//
//

@class NetRequestDTO;

#import "Emulation.h"
#import "IVanilaObject.h"

@protocol IPollingRequestHost < IVanilaObject, NSObject >
- (void)onPollingTriggerWithNetRequestDTO:(NetRequestDTO *)netRequestDTO;
@end

#define ComJvanilaMobileSyncIPollingRequestHost IPollingRequestHost
