//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/core/collection/IPredicate.java
//
//

#import "Emulation.h"
#import "ICloneableObject.h"

@protocol IPredicate < ICloneableObject, NSObject >
- (id<IPredicate>)addToPredicateWithNSString:(NSString *)field
                                                         withNSString:(NSString *)condition
                                                         withNSString:(NSString *)fieldValue;
- (id<IPredicate>)addToPredicateWithIPredicate:(id<IPredicate>)predicate;
@end

#define ComJvanilaCoreCollectionIPredicate IPredicate
