//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/job/IPrioritable.java
//
//

#import "Emulation.h"

@protocol IPrioritable < NSObject >
- (int)getPriority;
@end

#define ComJvanilaMobileJobIPrioritable IPrioritable
