//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/location/IRoundCap.java
//
//

#import "Emulation.h"
#import "ICap.h"

@protocol IRoundCap < ICap, NSObject >
@end

#define ComJvanilaMobileLocationIRoundCap IRoundCap
