//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/storage/ISecureSqliteAccessor.java
//
//

#import "Emulation.h"
#import "ISqliteAccessor.h"

@protocol ISecureSqliteAccessor < ISqliteAccessor, NSObject >
- (void)openSqliteDatabaseWithWithNSString:(NSString *)secretKey;
- (void)openSqliteDatabaseSynchronouslyWithNSString:(NSString *)secretKey;
- (NSString *)getSecretKey;
- (void)updateSecretKeyWithNSString:(NSString *)secretKey;
@end

#define ComJvanilaMobileStorageISecureSqliteAccessor ISecureSqliteAccessor
