//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/core/text/ISpannableStringBuilder.java
//
//

#import "Emulation.h"
#import "IVanilaObject.h"

@protocol ISpannableStringBuilder < IVanilaObject, NSObject >
- (id<ISpannableStringBuilder>)setForegroundColorSpanWithNSString:(NSString *)color
                                                                                   withInt:(int)indexOfSpanText
                                                                                   withInt:(int)spanTextLength;
- (id<ISpannableStringBuilder>)setStyleSpanWithInt:(int)typeFaceStyle
                                                                    withInt:(int)indexOfSpanText
                                                                    withInt:(int)spanTextLength;
- (id<ISpannableStringBuilder>)setSizeSpanWithInt:(int)fontSize
                                                                   withInt:(int)indexOfSpanText
                                                                   withInt:(int)spanTextLength;
- (id<ISpannableStringBuilder>)appendStringWithNSString:(NSString *)str;
- (id<ISpannableStringBuilder>)appendCharWithUnichar:(char)chr;
- (id<ISpannableStringBuilder>)appendIntWithInt:(int)integer;
- (id<ISpannableStringBuilder>)appendDoubleWithDouble:(double)doubleF;
- (id<ISpannableStringBuilder>)appendLongWithLongInt:(long long int)lng;
- (id<ISpannableStringBuilder>)prependStringWithNSString:(NSString *)str;
- (int)length;
- (id<ISpannableStringBuilder>)prependCharWithUnichar:(char)chr;
- (id<ISpannableStringBuilder>)prependIntWithInt:(int)integer;
- (id<ISpannableStringBuilder>)prependLongWithLongInt:(long long int)lng;
- (id<ISpannableStringBuilder>)appendObjectWithId:(id)object;
- (id<ISpannableStringBuilder>)setStringWithNSString:(NSString *)str;
- (int)indexOfWithNSString:(NSString *)spanText;
@end

#define ComJvanilaCoreTextISpannableStringBuilder ISpannableStringBuilder
