//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/storage/ISqliteCursor.java
//
//


@class IOSObjectArray;

#import "Emulation.h"
#import "IVanilaObject.h"

#define ISqliteCursor_FIELD_TYPE_BLOB 4
#define ISqliteCursor_FIELD_TYPE_FLOAT 2
#define ISqliteCursor_FIELD_TYPE_INTEGER 1
#define ISqliteCursor_FIELD_TYPE_NULL 0
#define ISqliteCursor_FIELD_TYPE_STRING 3

@protocol ISqliteCursor < IVanilaObject, NSObject >
- (int)getCount;
- (int)getPosition;
- (BOOL)moveWithInt:(int)offset;
- (BOOL)moveToPositionWithInt:(int)position;
- (BOOL)moveToFirst;
- (BOOL)moveToLast;
- (BOOL)moveToNext;
- (BOOL)moveToPrevious;
- (BOOL)isFirst;
- (BOOL)isLast;
- (BOOL)isBeforeFirst;
- (BOOL)isAfterLast;
- (int)getColumnIndexWithNSString:(NSString *)columnName;
- (int)getColumnIndexOrThrowWithNSString:(NSString *)columnName;
- (NSString *)getColumnNameWithInt:(int)columnIndex;
- (NSMutableArray *)getColumnNames;
- (int)getColumnCount;
- (NSData *)getBlobWithInt:(int)columnIndex;
- (NSString *)getStringWithInt:(int)columnIndex;
- (short int)getShortWithInt:(int)columnIndex;
- (int)getIntWithInt:(int)columnIndex;
- (long long int)getLongWithInt:(int)columnIndex;
- (float)getFloatWithInt:(int)columnIndex;
- (double)getDoubleWithInt:(int)columnIndex;
- (int)getTypeWithInt:(int)columnIndex;
- (BOOL)isNullWithInt:(int)columnIndex;
- (void)close;
- (BOOL)isClosed;
@end

@interface ISqliteCursor : NSObject {
}
+ (int)FIELD_TYPE_NULL;
+ (int)FIELD_TYPE_INTEGER;
+ (int)FIELD_TYPE_FLOAT;
+ (int)FIELD_TYPE_STRING;
+ (int)FIELD_TYPE_BLOB;
@end

#define ComJvanilaMobileStorageISqliteCursor ISqliteCursor
