//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/storage/ISqliteOpenListener.java
//
//

@protocol ISqliteAccessor;

#import "Emulation.h"

@protocol ISqliteOpenListener < NSObject >
- (void)onSQLiteDatabaseFailedToOpenWithISqliteAccessor:(id<ISqliteAccessor>)sqliteAccessor;
- (void)onSQLiteDatabaseOpenWithISqliteAccessor:(id<ISqliteAccessor>)sqliteAccessor;
- (void)onSQLiteDatabaseCloseWithISqliteAccessor:(id<ISqliteAccessor>)sqliteAccessor;
- (BOOL)isSqliteAccessible;
@end

#define ComJvanilaMobileStorageISqliteOpenListener ISqliteOpenListener
