//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/storage/ISqliteAccessor.java
//
//

@protocol IGenericList;
@protocol ISqliteOpenListener;

#import "Emulation.h"
#import "IVanilaObject.h"

@protocol ISqliteAccessor < IVanilaObject, NSObject >
- (void)initSqliteAccessorWithWithNSString:(NSString *)databaseName
                                   withInt:(int)dbVersion
 withIGenericList:(id<IGenericList>)createSchemaFileNames
 withIGenericList:(id<IGenericList>)deleteSchemaFileNames
withISqliteOpenListener:(id<ISqliteOpenListener>)callback ;
- (BOOL)isCorrupted;
- (BOOL)isOpening;
- (BOOL)isSqliteDatabaseOpen;
- (void)closeSqliteDatabase;
- (void)upgradeTableSchemaWithInt:(int)oldVersion
                          withInt:(int)newVersion
withIGenericList:(id<IGenericList>)oldVersionDeleteSchemaFileNames;
- (void)setCallbackWithISqliteOpenListener:(id<ISqliteOpenListener>)callback;
- (id<ISqliteOpenListener>)getCallback;
- (void)openSqliteDatabase;
- (void)openSqliteDatabaseSynchronously;
- (BOOL)isSecure;
- (int)getMigratedFromVersionNumber;
@end

#define ComJvanilaMobileStorageISqliteAccessor ISqliteAccessor
