//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/location/ISquareCap.java
//
//

#import "Emulation.h"
#import "ICap.h"

@protocol ISquareCap < ICap, NSObject >
@end

#define ComJvanilaMobileLocationISquareCap ISquareCap
