//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/core/IStringUtils.java
//
//


@class IOSObjectArray;
@protocol IGenericList;

#import "Emulation.h"
#import "IVanilaObject.h"

@protocol IStringUtils < IVanilaObject, NSObject >
- (BOOL)isNullOrEmptyWithNSString:(NSString *)str;
- (BOOL)isNumberWithNSString:(NSString *)str;
- (int)lengthOfWithNSString:(NSString *)str;
- (char)getCharAtWithNSString:(NSString *)source
                         withInt:(int)index;
- (NSString *)trimStringWithNSString:(NSString *)source;
- (NSString *)subStringWithNSString:(NSString *)source
                            withInt:(int)start
                            withInt:(int)end;
- (NSString *)toLowerCaseOfXWithNSString:(NSString *)xStr;
- (NSString *)toUpperCaseOfXWithNSString:(NSString *)xStr;
- (NSString *)fromBytesWithNSData:(NSData *)bytes;
- (NSData *)toBytesWithNSString:(NSString *)value;
- (NSString *)toBase64WithNSData:(NSData *)data;
- (NSData *)fromBase64WithNSString:(NSString *)encodedData;
- (NSString *)toHexStringWithNSData:(NSData *)bytes;
- (NSString *)toCSVStringWithIGenericList:(id<IGenericList>)stringlist;
- (NSString *)toCSVStringWithIGenericList:(id<IGenericList>)stringlist
                                                      withNSString:(NSString *)delimiter;
- (int)parseIntWithNSString:(NSString *)intString;
- (long long int)parseLongWithNSString:(NSString *)str;
- (float)parseFloatWithNSString:(NSString *)floatString;
- (double)parseDoubleWithNSString:(NSString *)doubleString;
- (NSString *)formatStringWithNSString:(NSString *)stringWithFormatSpecifiers
                     , ... NS_REQUIRES_NIL_TERMINATION;
- (BOOL)areXAndYEqualWithNSString:(NSString *)str1
                     withNSString:(NSString *)str2;
- (int)indexOfYInXWithNSString:(NSString *)yStr
                  withNSString:(NSString *)xStr;
- (int)lastIndexOfYInXWithNSString:(NSString *)yStr
                      withNSString:(NSString *)xStr;
- (BOOL)isXContainsYWithNSString:(NSString *)xStr
                    withNSString:(NSString *)yStr;
- (NSString *)removeLastOccurenceOfYInXWithNSString:(NSString *)yStr
                                       withNSString:(NSString *)xStr;
- (NSString *)replaceAllOccuarencesOfYWithZInXWithNSString:(NSString *)yStr
                                              withNSString:(NSString *)zStr
                                              withNSString:(NSString *)xStr;
- (NSString *)replaceAllByRegexWithYInXWithNSString:(NSString *)regex
                                       withNSString:(NSString *)yStr
                                       withNSString:(NSString *)xStr;
- (BOOL)isXStartsWithYWithNSString:(NSString *)xStr
                      withNSString:(NSString *)yStr;
- (BOOL)isXEndsWithYWithNSString:(NSString *)xStr
                    withNSString:(NSString *)yStr;
- (id<IGenericList>)splitXWithYWithNSString:(NSString *)xStr
                                                        withNSString:(NSString *)yStr;
- (int)compareToIgnoreCaseOfYWithXWithNSString:(NSString *)yStr
                                  withNSString:(NSString *)xStr;
- (BOOL)isXMatchesTheRegexPatternYWithNSString:(NSString *)xStr
                                  withNSString:(NSString *)yPatternStr;
@end

#define ComJvanilaCoreIStringUtils IStringUtils
