//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/core/datatype/IStringBuilder.java
//
//

#import "Emulation.h"
#import "IVanilaObject.h"

@protocol IStringBuilder < IVanilaObject, NSObject >
- (id<IStringBuilder>)appendStringWithNSString:(NSString *)str;
- (id<IStringBuilder>)appendCharWithUnichar:(char)chr;
- (id<IStringBuilder>)appendIntWithInt:(int)integer;
- (id<IStringBuilder>)appendDoubleWithDouble:(double)doubleF;
- (id<IStringBuilder>)appendLongWithLongInt:(long long int)lng;
- (id<IStringBuilder>)prependStringWithNSString:(NSString *)str;
- (id<IStringBuilder>)prependCharWithUnichar:(char)chr;
- (id<IStringBuilder>)prependIntWithInt:(int)integer;
- (id<IStringBuilder>)prependLongWithLongInt:(long long int)lng;
- (id<IStringBuilder>)appendObjectWithId:(id)object;
- (id<IStringBuilder>)setStringWithNSString:(NSString *)str;
- (int)length;
@end

#define ComJvanilaCoreDatatypeIStringBuilder IStringBuilder
