//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/core/collection/ISynchronizedList.java
//
//

@protocol ISynchronizedList_LoopItemCallback;

#import "Emulation.h"
#import "IGenericList.h"

@protocol ISynchronizedList < IGenericList, NSObject >
- (id<IGenericList>)list;
- (void)setListWithIGenericList:(id<IGenericList>)list;
- (void)replaceWithId:(id)element;
- (void)foreachWithISynchronizedList_LoopItemCallback:(id<ISynchronizedList_LoopItemCallback>)callback;
@end

#define ComJvanilaCoreCollectionISynchronizedList ISynchronizedList

@protocol ISynchronizedList_LoopItemCallback < NSObject >
- (BOOL)itemWithId:(id)item;
@end
