//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/sync/ISyncAdapterLoadCallback.java
//
//

@protocol ISyncAdapter;

#import "Emulation.h"

@protocol ISyncAdapterLoadCallback < NSObject >
- (void)onSyncAdapterLoadedWithISyncAdapter:(id<ISyncAdapter>)syncAdapter;
@end

#define ComJvanilaMobileSyncISyncAdapterLoadCallback ISyncAdapterLoadCallback
