//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/storage/ISyncStatsDAO.java
//
//

@class SyncStatsDTO;
@protocol IGenericList;

#import "Emulation.h"
#import "ITransactionHandler.h"

@protocol ISyncStatsDAO < ITransactionHandler, NSObject >
- (int)createRecordWithSyncStatsDTO:(SyncStatsDTO *)dto;
- (BOOL)deleteSyncStatsByEndPointWithNSString:(NSString *)endPoint;
- (BOOL)deleteSyncStatsByIdWithNSString:(NSString *)statUuid;
- (BOOL)deleteSyncStatsByIdAndPublishWithNSString:(NSString *)statUuid
                                         withBOOL:(BOOL)isPublishable;
- (BOOL)deleteAll;
- (int)updateRecordWithSyncStatsDTO:(SyncStatsDTO *)dto;
- (int)getRecordSize;
- (id<IGenericList>)getAllRecords;
- (SyncStatsDTO *)getRecordWithNSString:(NSString *)statUuid;
- (SyncStatsDTO *)getRecordByEntityUuidWithNSString:(NSString *)entityUuid
                                                                withNSString:(NSString *)endPoint;
@end

#define ComJvanilaMobileStorageISyncStatsDAO ISyncStatsDAO
