//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/core/locale/ITimeZone.java
//
//

#import "Emulation.h"
#import "ICloneableObject.h"

@protocol ITimeZone < ICloneableObject, NSObject >
- (void)setTimeZoneIdForWithNSString:(NSString *)olsonIdOrGmtOffset
                             withInt:(int)timeZoneOffsetInMins;
- (NSString *)getOlsonIdOrGmtOffset;
- (int)getTimeZoneOffsetInMins;
- (id<ITimeZone>)getUserTimeZone;
- (BOOL)isOlsonIdAvailableWithNSString:(NSString *)olsonId;
- (NSString *)getTimeZoneOffsetInGMTPlusOrMinusHHColonMMForWithInt:(int)timeZoneOffsetInMinutes;
@end

#define ComJvanilaCoreLocaleITimeZone ITimeZone
