//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/storage/ITransactionHandler.java
//
//

#import "Emulation.h"
#import "IVanilaObject.h"

@protocol ITransactionHandler < IVanilaObject, NSObject >
- (void)startTransaction;
- (void)commitTransaction;
@end

#define ComJvanilaMobileStorageITransactionHandler ITransactionHandler
