//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/core/text/ITypeface.java
//
//

#import "Emulation.h"

#define ITypeface_BOLD 1
#define ITypeface_BOLD_ITALIC 3
#define ITypeface_ITALIC 2
#define ITypeface_NORMAL 0

@protocol ITypeface < NSObject >
@end

@interface ITypeface : NSObject {
}
+ (int)NORMAL;
+ (int)BOLD;
+ (int)ITALIC;
+ (int)BOLD_ITALIC;
@end

#define ComJvanilaCoreTextITypeface ITypeface
