//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/core/util/IUUIDGenerator.java
//
//

#import "Emulation.h"
#import "IVanilaObject.h"

@protocol IUUIDGenerator < IVanilaObject, NSObject >
- (NSString *)getRandomUUID;
- (BOOL)isUUIDWithNSString:(NSString *)uuid;
@end

#define ComJvanilaCoreUtilIUUIDGenerator IUUIDGenerator
