//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/core/objectflavor/IVanilaObject.java
//
//

#import "Emulation.h"


@protocol IVanilaObject <  NSObject >
- (NSString *)getClassName;
- (NSString *)stringify;
@end

#define ComJvanilaCoreObjectflavorIVanilaObject IVanilaObject
