//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/core/memorymanagement/IWeakReference.java
//
//

#import "Emulation.h"
#import "IVanilaObject.h"

@protocol IWeakReference < IVanilaObject, NSObject >
- (void)setWithId:(id)reference;
- (id)get;
- (void)release__;
@end

#define ComJvanilaCoreMemorymanagementIWeakReference IWeakReference
