//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/job/JobManager.java
//
//

@protocol IJobHandler;

#import "Emulation.h"
#import "VanilaObject.h"

@interface JobManager : VanilaObject {
}

+ (id<IJobHandler>)sJobHandler;
+ (void)setSJobHandlerWithIJobHandler:(id<IJobHandler>)sJobHandler;
+ (void)setJobHandlerWithIJobHandler:(id<IJobHandler>)handler;
+ (id<IJobHandler>)getJobHandler;
@end

typedef JobManager ComJvanilaMobileJobJobManager;
