//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/job/JobState.java
//
//

#import "Emulation.h"
#import "VanilaObject.h"

#define JobState_STATE_AWAITING 1
#define JobState_STATE_CANCELLED 3
#define JobState_STATE_CREATED 0
#define JobState_STATE_EXECUTING 2
#define JobState_STATE_FINISHED 4

@interface JobState : VanilaObject {
 @public
  int state_;
}

@property (nonatomic, assign) int state;

+ (int)STATE_CREATED;
+ (int)STATE_AWAITING;
+ (int)STATE_EXECUTING;
+ (int)STATE_CANCELLED;
+ (int)STATE_FINISHED;
- (id)initWithInt:(int)state;
+ (JobState *)asStateCreated;
+ (JobState *)asStateAwaiting;
+ (JobState *)asStateExecuting;
+ (JobState *)asStateCancelled;
+ (JobState *)asStateFinished;
@end

typedef JobState ComJvanilaMobileJobJobState;
