//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/location/JointType.java
//
//

#import "Emulation.h"

#define JointType_BEVEL 1
#define JointType_DEFAULT 0
#define JointType_ROUND 2

@interface JointType : NSObject {
}

+ (int)DEFAULT;
+ (int)BEVEL;
+ (int)ROUND;
@end

typedef JointType ComJvanilaMobileLocationJointType;
