//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/storage/KeyValueStore.java
//
//

@class KeyValueLookUpDTO;
@class LookUpDAO;

@protocol IMobilePlatformFactory;

#import "Emulation.h"

@interface KeyValueStore : NSObject {
 @public
  id<IMobilePlatformFactory> mMobilePlatformFactory_;
  LookUpDAO *mKeyValueDAO_;
  KeyValueLookUpDTO *mKeyValueLookUpDTO_;
}

@property (nonatomic, strong) id<IMobilePlatformFactory> mMobilePlatformFactory;
@property (nonatomic, strong) LookUpDAO *mKeyValueDAO;
@property (nonatomic, strong) KeyValueLookUpDTO *mKeyValueLookUpDTO;

+ (KeyValueStore *)sInstance;
+ (void)setSInstanceWithKeyValueStore:(KeyValueStore *)sInstance;
+ (KeyValueStore *)getInstance;
- (id)init;
- (void)init__ ;
- (void)release__;
- (void)putIntWithNSString:(NSString *)key
                   withInt:(int)value;
- (void)putFloatWithNSString:(NSString *)key
                   withFloat:(float)value;
- (void)putLongWithNSString:(NSString *)key
                withLongInt:(long long int)value;
- (void)putBooleanWithNSString:(NSString *)key
                      withBOOL:(BOOL)value;
- (void)putStringWithNSString:(NSString *)key
                 withNSString:(NSString *)value;
- (void)putNSCodingWithNSString:(NSString *)key
             withNSCoding:(id<NSCoding>)value;
- (void)removeWithNSString:(NSString *)key;
- (void)removeAll;
- (int)getIntWithNSString:(NSString *)key
                  withInt:(int)defValue;
- (long long int)getLongWithNSString:(NSString *)key
                         withLongInt:(long long int)defValue;
- (float)getFloatWithNSString:(NSString *)key
                    withFloat:(float)defValue;
- (BOOL)getBooleanWithNSString:(NSString *)key
                      withBOOL:(BOOL)defValue;
- (NSString *)getStringWithNSString:(NSString *)key
                       withNSString:(NSString *)defValue;
- (id<NSCoding>)getNSCodingWithNSString:(NSString *)key;
- (BOOL)containsWithNSString:(NSString *)key;
@end

typedef KeyValueStore ComJvanilaMobileStorageKeyValueStore;
