//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/core/collection/ListBehaviorType.java
//
//

#import "Emulation.h"
#import "VanilaObject.h"

#define ListBehaviorType_BEHAVIOR_TYPE_ARRAYDEQUE 8
#define ListBehaviorType_BEHAVIOR_TYPE_ARRAY_LIST 0
#define ListBehaviorType_BEHAVIOR_TYPE_HASHED_SET 3
#define ListBehaviorType_BEHAVIOR_TYPE_LINKED_HASHED_SET 4
#define ListBehaviorType_BEHAVIOR_TYPE_LINKED_LIST 2
#define ListBehaviorType_BEHAVIOR_TYPE_PRIORITY_QUEUE 6
#define ListBehaviorType_BEHAVIOR_TYPE_STACK 7
#define ListBehaviorType_BEHAVIOR_TYPE_TREE_SET 5
#define ListBehaviorType_BEHAVIOR_TYPE_VECTOR 1

@interface ListBehaviorType : VanilaObject {
 @public
  int behaviorType_;
}

@property (nonatomic, assign) int behaviorType;

+ (NSString *)CLASS_NAME;
+ (int)BEHAVIOR_TYPE_ARRAY_LIST;
+ (int)BEHAVIOR_TYPE_VECTOR;
+ (int)BEHAVIOR_TYPE_LINKED_LIST;
+ (int)BEHAVIOR_TYPE_HASHED_SET;
+ (int)BEHAVIOR_TYPE_LINKED_HASHED_SET;
+ (int)BEHAVIOR_TYPE_TREE_SET;
+ (int)BEHAVIOR_TYPE_PRIORITY_QUEUE;
+ (int)BEHAVIOR_TYPE_STACK;
+ (int)BEHAVIOR_TYPE_ARRAYDEQUE;
- (id)initWithInt:(int)behaviorType;
- (BOOL)isArrayList;
- (BOOL)isVector;
- (BOOL)isLinkedList;
- (BOOL)isHashedSet;
- (BOOL)isLinkedHashedSet;
- (BOOL)isTreeSet;
@end

typedef ListBehaviorType ComJvanilaCoreCollectionListBehaviorType;
