//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/storage/LookUpDAO.java
//
//

@class DataObject;
@protocol IFileAccessor;

#import "Emulation.h"
#import "VanilaObject.h"

@interface LookUpDAO : VanilaObject {
 @public
  id<IFileAccessor> mFileAccessor_;
  id mLock_;
  NSString *mFileName_;
  DataObject *mLookUpDTO_;
}

@property (nonatomic, strong) id<IFileAccessor> mFileAccessor;
@property (nonatomic, strong) id mLock;
@property (nonatomic, copy) NSString *mFileName;
@property (nonatomic, strong) DataObject *mLookUpDTO;

+ (NSString *)CLASS_NAME;
- (id)initWithNSString:(NSString *)fileName
withIFileAccessor:(id<IFileAccessor>)fileAccessor;
- (void)writeWithId:(DataObject *)objLookUpDto
       withNSString:(NSString *)key;
- (DataObject *)readWithNSString:(NSString *)key;
- (void)deleteIfAvailable;
- (BOOL)isAvailable;
@end

typedef LookUpDAO ComJvanilaMobileStorageLookUpDAO;
