//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/core/collection/MapBehaviorType.java
//
//

#import "Emulation.h"
#import "VanilaObject.h"

#define MapBehaviorType_BEHAVIOR_TYPE_HASHMAP 0
#define MapBehaviorType_BEHAVIOR_TYPE_HASHTABLE 1
#define MapBehaviorType_BEHAVIOR_TYPE_IDENTITY_HASHMAP 2
#define MapBehaviorType_BEHAVIOR_TYPE_LINKED_HASHMAP 3
#define MapBehaviorType_BEHAVIOR_TYPE_TREE_MAP 4
#define MapBehaviorType_BEHAVIOR_TYPE_WEAK_HASHMAP 5

@interface MapBehaviorType : VanilaObject {
 @public
  int behaviorType_;
}

@property (nonatomic, assign) int behaviorType;

+ (NSString *)CLASS_NAME;
+ (int)BEHAVIOR_TYPE_HASHMAP;
+ (int)BEHAVIOR_TYPE_HASHTABLE;
+ (int)BEHAVIOR_TYPE_IDENTITY_HASHMAP;
+ (int)BEHAVIOR_TYPE_LINKED_HASHMAP;
+ (int)BEHAVIOR_TYPE_TREE_MAP;
+ (int)BEHAVIOR_TYPE_WEAK_HASHMAP;
- (id)initWithInt:(int)behaviorType;
- (BOOL)isHashMap;
- (BOOL)isHashtable;
- (BOOL)isIdentityHashMap;
- (BOOL)isLinkedHashMap;
- (BOOL)isTreeMap;
- (BOOL)isWeakHashMap;
@end

typedef MapBehaviorType ComJvanilaCoreCollectionMapBehaviorType;
