//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/location/MarkerParams.java
//
//

@class VanilaLocation;
@protocol IComparableObject;

#import "Emulation.h"
#import "ComparableObject.h"

@interface MarkerParams : ComparableObject {
 @public
  VanilaLocation *position_;
  NSString *title_;
  NSString *snippet_;
  id wrappedIcon_;
  float anchorU_;
  float anchorV_;
  BOOL draggable_;
  BOOL visible_;
  BOOL flat_;
  float rotation_;
  float infoWindowAnchorU_;
  float infoWindowAnchorV_;
  float alpha_;
  int zIndex_;
  NSString *identifier_;
  id tag_;
}

@property (nonatomic, strong) VanilaLocation *position;
@property (nonatomic, copy) NSString *title;
@property (nonatomic, copy) NSString *snippet;
@property (nonatomic, strong) id wrappedIcon;
@property (nonatomic, assign) float anchorU;
@property (nonatomic, assign) float anchorV;
@property (nonatomic, assign) BOOL draggable;
@property (nonatomic, assign) BOOL visible;
@property (nonatomic, assign) BOOL flat;
@property (nonatomic, assign) float rotation;
@property (nonatomic, assign) float infoWindowAnchorU;
@property (nonatomic, assign) float infoWindowAnchorV;
@property (nonatomic, assign) float alpha;
@property (nonatomic, assign) int zIndex;
@property (nonatomic, copy) NSString *identifier;
@property (nonatomic, strong) id tag;

- (id)init;
- (BOOL)isEqualsToWithIComparableObject:(id<IComparableObject>)o;
- (NSUInteger)hashOfObject;
@end

typedef MarkerParams ComJvanilaMobileLocationMarkerParams;
