//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/MobileBuildInfo.java
//
//

#import "Emulation.h"
#import "BuildInfo.h"

@interface MobileBuildInfo : BuildInfo {
 @public
  NSString *serverBaseUrl_;
  NSString *serverApiBaseUrl_;
  NSString *serverMqttBaseUrl_;
  NSString *appPublishedStoreUrl_;
}

@property (nonatomic, copy) NSString *serverBaseUrl;
@property (nonatomic, copy) NSString *serverApiBaseUrl;
@property (nonatomic, copy) NSString *serverMqttBaseUrl;
@property (nonatomic, copy) NSString *appPublishedStoreUrl;

+ (NSString *)CLASS_NAME;
- (NSString *)stringify;
@end

typedef MobileBuildInfo ComJvanilaMobileMobileBuildInfo;
