//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/MobilePlatformFactoryLocator.java
//
//

@protocol IMobilePlatformFactory;

#import "Emulation.h"
#import "VanilaObject.h"

@interface MobilePlatformFactoryLocator : VanilaObject {
}

+ (id<IMobilePlatformFactory>)sMobilePlatformFactory;
+ (void)setSMobilePlatformFactoryWithIMobilePlatformFactory:(id<IMobilePlatformFactory>)sMobilePlatformFactory;
+ (void)setMobilePlatformFactoryWithIMobilePlatformFactory:(id<IMobilePlatformFactory>)platformFactory;
+ (id<IMobilePlatformFactory>)getMobilePlatformFactory;
@end

typedef MobilePlatformFactoryLocator ComJvanilaMobileMobilePlatformFactoryLocator;
