//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/sync/events/NetRequestSyncProgressEvent.java
//
//

#import "Emulation.h"
#import "DataObject.h"

#define NetRequestSyncProgressEvent_STATE_CANCELLED 5
#define NetRequestSyncProgressEvent_STATE_COMPLETED 7
#define NetRequestSyncProgressEvent_STATE_FAILED 6
#define NetRequestSyncProgressEvent_STATE_IDLE 0
#define NetRequestSyncProgressEvent_STATE_PAUSED 3
#define NetRequestSyncProgressEvent_STATE_PROGRESSING 2
#define NetRequestSyncProgressEvent_STATE_RESUMED 4
#define NetRequestSyncProgressEvent_STATE_STARTED 1

@interface NetRequestSyncProgressEvent : DataObject {
 @public
  NSString *mRequestType_;
  NSString *mContainedObjectUniqueId_;
  DataObject *mProcessedResultDTO_;
  long long int bytesCurrent_;
  long long int bytesTotal_;
  int progressState_;
}

@property (nonatomic, copy) NSString *mRequestType;
@property (nonatomic, copy) NSString *mContainedObjectUniqueId;
@property (nonatomic, strong) DataObject *mProcessedResultDTO;
@property (nonatomic, assign) long long int bytesCurrent;
@property (nonatomic, assign) long long int bytesTotal;
@property (nonatomic, assign) int progressState;

+ (NSString *)CLASS_NAME;
+ (int)STATE_IDLE;
+ (int)STATE_STARTED;
+ (int)STATE_PROGRESSING;
+ (int)STATE_PAUSED;
+ (int)STATE_RESUMED;
+ (int)STATE_CANCELLED;
+ (int)STATE_FAILED;
+ (int)STATE_COMPLETED;
- (id)init;
- (NSString *)description;
@end

typedef NetRequestSyncProgressEvent ComJvanilaMobileSyncEventsNetRequestSyncProgressEvent;
