//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/sync/events/NetRequestFailedForMaxTimesEvent.java
//
//

@class NetRequestDTO;

#import "Emulation.h"
#import "DataObject.h"

@interface NetRequestFailedForMaxTimesEvent : DataObject {
 @public
  NetRequestDTO *mNetRequest_;
}

@property (nonatomic, strong) NetRequestDTO *mNetRequest;

+ (NSString *)CLASS_NAME;
@end

typedef NetRequestFailedForMaxTimesEvent ComJvanilaMobileSyncEventsNetRequestFailedForMaxTimesEvent;
