//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/mvp/NullController.java
//
//

@protocol IView;

#import "Emulation.h"
#import "Presenter.h"

@interface NullController : Presenter {
}

- (id)initWithId:(id)view;
@end

typedef NullController ComJvanilaMobileMvpNullController;
