//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/mvp/NullBinder.java
//
//

@class IOSObjectArray;
@protocol IBindableView;

#import "Emulation.h"
#import "DataBinder.h"

@interface NullBinder : DataBinder {
}

- (id)initWithIBindableView:(id<IBindableView>)view;
- (BOOL)onBindWithObjects:(id)models,... NS_REQUIRES_NIL_TERMINATION;
- (BOOL)onBindWithNSArray:(NSArray *)models;
@end

typedef NullBinder ComJvanilaMobileMvpNullBinder;
