//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/job/PeriodicAsyncJob.java
//
//

#import "Emulation.h"
#import "AsyncJob.h"

@interface PeriodicAsyncJob : AsyncJob {
}

- (id)init;
@end

typedef PeriodicAsyncJob ComJvanilaMobileJobPeriodicAsyncJob;
