//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/core/PlatformFactoryLocator.java
//
//

@protocol IPlatformFactory;

#import "Emulation.h"
#import "VanilaObject.h"

@interface PlatformFactoryLocator : VanilaObject {
}

+ (id<IPlatformFactory>)sPlatformFactory;
+ (void)setSPlatformFactoryWithIPlatformFactory:(id<IPlatformFactory>)sPlatformFactory;
+ (void)setPlatformFactoryWithIPlatformFactory:(id<IPlatformFactory>)platformFactory;
+ (id<IPlatformFactory>)getPlatformFactory;
@end

typedef PlatformFactoryLocator ComJvanilaCorePlatformFactoryLocator;
