//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/core/PlatformInfo.java
//
//

#import "Emulation.h"
#import "VanilaObject.h"

@interface PlatformInfo : VanilaObject {
 @public
  NSString *osName_;
  NSString *osVersion_;
  NSString *deviceModel_;
  NSString *deviceManufacturer_;
}

@property (nonatomic, copy) NSString *osName;
@property (nonatomic, copy) NSString *osVersion;
@property (nonatomic, copy) NSString *deviceModel;
@property (nonatomic, copy) NSString *deviceManufacturer;

+ (NSString *)CLASS_NAME;
- (id)init;
- (NSString *)stringify;
@end

typedef PlatformInfo ComJvanilaCorePlatformInfo;
