//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/location/PolygonParams.java
//
//

@protocol IComparableObject;
@protocol IGenericList;

#import "Emulation.h"
#import "ComparableObject.h"

@interface PolygonParams : ComparableObject {
 @public
  id<IGenericList> locations_;
  id<IGenericList> hole_;
  BOOL isClickable_;
  NSString *fillColor_;
  BOOL isGeodesic_;
  NSString *strokeColor_;
  float strokeWidth_;
  BOOL isVisible_;
  int strokeJointType_;
  id<IGenericList> strokePattern_;
  float zIndex_;
  NSString *identifier_;
  id tag_;
}

@property (nonatomic, strong) id<IGenericList> locations;
@property (nonatomic, strong) id<IGenericList> hole;
@property (nonatomic, assign) BOOL isClickable;
@property (nonatomic, copy) NSString *fillColor;
@property (nonatomic, assign) BOOL isGeodesic;
@property (nonatomic, copy) NSString *strokeColor;
@property (nonatomic, assign) float strokeWidth;
@property (nonatomic, assign) BOOL isVisible;
@property (nonatomic, assign) int strokeJointType;
@property (nonatomic, strong) id<IGenericList> strokePattern;
@property (nonatomic, assign) float zIndex;
@property (nonatomic, copy) NSString *identifier;
@property (nonatomic, strong) id tag;

- (id)init;
- (BOOL)isEqualsToWithIComparableObject:(id<IComparableObject>)o;
- (NSUInteger)hashOfObject;
@end

typedef PolygonParams ComJvanilaMobileLocationPolygonParams;
