//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/location/PolylineParams.java
//
//

@protocol IComparableObject;
@protocol IGenericList;

#import "Emulation.h"
#import "ComparableObject.h"

@interface PolylineParams : ComparableObject {
 @public
  float width_;
  float zIndex_;
  NSString *color_;
  BOOL isClickable_;
  BOOL isGeodesic_;
  BOOL isVisible_;
  id<IGenericList> locations_;
  int jointType_;
  id<IGenericList> pattern_;
  NSString *identifier_;
  id tag_;
}

@property (nonatomic, assign) float width;
@property (nonatomic, assign) float zIndex;
@property (nonatomic, copy) NSString *color;
@property (nonatomic, assign) BOOL isClickable;
@property (nonatomic, assign) BOOL isGeodesic;
@property (nonatomic, assign) BOOL isVisible;
@property (nonatomic, strong) id<IGenericList> locations;
@property (nonatomic, assign) int jointType;
@property (nonatomic, strong) id<IGenericList> pattern;
@property (nonatomic, copy) NSString *identifier;
@property (nonatomic, strong) id tag;

- (id)init;
- (BOOL)isEqualsToWithIComparableObject:(id<IComparableObject>)o;
- (NSUInteger)hashOfObject;
@end

typedef PolylineParams ComJvanilaMobileLocationPolylineParams;
