//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/mvp/Presenter.java
//
//

@class IOSObjectArray;
@class BuildInfo;
@protocol IAppHealthMonitor;
@protocol IApplication;
@protocol IEvent;
@protocol IEventBus;
@protocol IGenericList;
@protocol ILogger;
@protocol IMobilePlatformFactory;
@protocol IResourceProvider;
@protocol IStringUtils;
@protocol ISyncAdapter;
@protocol IView;
@protocol IWeakReference;

#import "Emulation.h"
#import "IEventSubscriber.h"
#import "IComparableObject.h"
#import "IDependenciesCallback.h"

@interface Presenter : NSObject < IComparableObject, IEventSubscriber, IDependenciesCallback > {
 @public
  NSString *TAG_;
  id<IWeakReference> mViewWeakRef_;
  id<IGenericList> mFragmentControllerList_;
  Presenter *mParentController_;
  BOOL mIsOnCreateCalled_;
  BOOL mIsOnStartCalled_;
  BOOL mIsOnResumeCalled_;
  BOOL mIsOnPauseCalled_;
  BOOL mIsOnStopCalled_;
  BOOL mIsDestroying_;
  BOOL mViewIsMovingOut_;
  id<IMobilePlatformFactory> mMobilePlatformFactory_;
  id<IApplication> mApplication_;
  id<IResourceProvider> mResourceProvider_;
  id<ISyncAdapter> mSyncAdapter_;
  id<IAppHealthMonitor> mAppHealthMonitor_;
  id<IStringUtils> mStringUtils_;
  id<IEventBus> mEventBus_;
  id<ILogger> mLogger_;
  BuildInfo *mBuildInfo_;
}

@property (nonatomic, copy) NSString *TAG;
@property (nonatomic, strong) id<IWeakReference> mViewWeakRef;
@property (nonatomic, strong) id<IGenericList> mFragmentControllerList;
@property (nonatomic, strong) Presenter *mParentController;
@property (nonatomic, assign) BOOL mIsOnCreateCalled;
@property (nonatomic, assign) BOOL mIsOnStartCalled;
@property (nonatomic, assign) BOOL mIsOnResumeCalled;
@property (nonatomic, assign) BOOL mIsOnPauseCalled;
@property (nonatomic, assign) BOOL mIsOnStopCalled;
@property (nonatomic, assign) BOOL mIsDestroying;
@property (nonatomic, assign) BOOL mViewIsMovingOut;
@property (nonatomic, strong) id<IMobilePlatformFactory> mMobilePlatformFactory;
@property (nonatomic, strong) id<IApplication> mApplication;
@property (nonatomic, strong) id<IResourceProvider> mResourceProvider;
@property (nonatomic, strong) id<ISyncAdapter> mSyncAdapter;
@property (nonatomic, strong) id<IAppHealthMonitor> mAppHealthMonitor;
@property (nonatomic, strong) id<IStringUtils> mStringUtils;
@property (nonatomic, strong) id<IEventBus> mEventBus;
@property (nonatomic, strong) id<ILogger> mLogger;
@property (nonatomic, strong) BuildInfo *mBuildInfo;

+ (NSString *)CLASS_NAME;
- (id)initWithId:(id)view;
- (void)initInternal ;
- (void)onCreate;
- (void)onCreateInternal;
- (void)onStart;
- (void)onStartSubscribe;
- (void)onStartInterceptable;
- (void)onResume;
- (void)onDependenciesResolving;
- (void)onDependenciesResolved;
- (void)onDependenciesResolvingFailed;
- (void)setViewWithId:(id)view;
- (id)getView;
- (void)setParentControllerWithPresenter:(Presenter *)presenter;
- (Presenter *)getParentController;
- (void)addFragmentControllerWithPresenter:(Presenter *)presenter;
- (void)removeFragmentControllerWithPresenter:(Presenter *)presenter;
- (BOOL)isFragmentControllerAddedWithPresenter:(Presenter *)presenter;
- (NSString *)getStringWithNSString:(NSString *)resId;
- (NSString *)getStringWithNSString:(NSString *)resId withNSArray:(NSArray *)params, ... NS_REQUIRES_NIL_TERMINATION;
- (BOOL)isInstanceOfWithClass:(Class )clazz;
- (BOOL)isEqualsToWithIComparableObject:(id<IComparableObject>)object;
- (NSUInteger)hashOfObject;
- (NSString *)getClassName;
- (NSString *)stringify;
- (void)onEventWithIEvent:(id<IEvent>)event;
- (void)onBackPressed;
- (void)onPause;
- (BOOL)isDestroying;
- (void)setViewIsMovingOutWithBOOL:(BOOL)movingOut;
- (BOOL)isViewMovingOut;
- (void)onStopUnsubscribe;
- (void)onDestroyUnsubscribe;
- (void)onStop;
- (void)onDestroy;
@end

typedef Presenter ComJvanilaMobileMvpPresenter;
