//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/core/util/PrimitiveBox.java
//
//

#import "Emulation.h"

@interface PrimitiveBox : NSObject {
 @public
  id value_;
}

@property (nonatomic, strong) id value;

- (id)init;
- (id)initWithId:(id)value;
- (void)setWithId:(id)value;
- (id)get;
@end

typedef PrimitiveBox ComJvanilaCoreUtilPrimitiveBox;
