//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/sync/events/QItemCountChangeEvent.java
//
//

#import "Emulation.h"
#import "DataObject.h"

@interface QItemCountChangeEvent : DataObject {
 @public
  int mQueueItemCount_;
}

@property (nonatomic, assign) int mQueueItemCount;

+ (NSString *)CLASS_NAME;
- (id)initWithInt:(int)queueItemCount;
@end

typedef QItemCountChangeEvent ComJvanilaMobileSyncEventsQItemCountChangeEvent;
