//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/core/locale/Resource.java
//
//

#import "Emulation.h"
#import "VanilaObject.h"

@interface Resource : VanilaObject {
 @public
  int resId_;
  NSString *resName_;
  NSString *type_;
}

@property (nonatomic, assign) int resId;
@property (nonatomic, copy) NSString *resName;
@property (nonatomic, copy) NSString *type;

+ (NSString *)TYPE_DRAWABLE;
+ (NSString *)TYPE_DIMENSION;
+ (NSString *)TYPE_COLOR;
+ (NSString *)TYPE_STRING;
+ (NSString *)getTYPE_BOOL;
+ (NSString *)TYPE_INTEGER;
- (id)initWithInt:(int)resId
     withNSString:(NSString *)resName
     withNSString:(NSString *)type;
@end

typedef Resource ComJvanilaCoreLocaleResource;
