//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/storage/SqliteLoadedEvent.java
//
//

#import "Emulation.h"
#import "DataObject.h"

#define SqliteLoadedEvent_FAILED 1
#define SqliteLoadedEvent_IDLE 0
#define SqliteLoadedEvent_SUCCESS 2

@interface SqliteLoadedEvent : DataObject {
 @public
  NSString *mDatabaseName_;
  int mState_;
}

@property (nonatomic, copy) NSString *mDatabaseName;
@property (nonatomic, assign) int mState;

+ (NSString *)CLASS_NAME;
+ (int)IDLE;
+ (int)FAILED;
+ (int)SUCCESS;
- (id)initWithNSString:(NSString *)databaseName
               withInt:(int)state;
@end

typedef SqliteLoadedEvent ComJvanilaMobileStorageSqliteLoadedEvent;
