//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/storage/SqliteObjectLostEvent.java
//
//

#import "Emulation.h"
#import "DataObject.h"

@interface SqliteObjectLostEvent : DataObject {
}

+ (NSString *)CLASS_NAME;
- (id)init;
@end

typedef SqliteObjectLostEvent ComJvanilaMobileStorageSqliteObjectLostEvent;
