//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/sync/SyncGateway.java
//
//

@class FailureResponseDTO;
@class NetRequestDTO;
@class NetResponseDTO;
@class SyncEntitiesDTO;
@protocol INetRequestQueue;
@protocol IPeriodicPollingPool;

#import "Emulation.h"
#import "VanilaObject.h"

@interface SyncGateway : VanilaObject {
 @public
  id<INetRequestQueue> mNetRequestQueue_;
  id<IPeriodicPollingPool> mPeriodicPollingPool_;
}

@property (nonatomic, strong) id<INetRequestQueue> mNetRequestQueue;
@property (nonatomic, strong) id<IPeriodicPollingPool> mPeriodicPollingPool;

+ (NSString *)CLASS_NAME;
- (id)initWithINetRequestQueue:(id<INetRequestQueue>)netRequestQueue
      withIPeriodicPollingPool:(id<IPeriodicPollingPool>)periodicPollingPool;
- (void)onSuccessWithNetResponseDTO:(NetResponseDTO *)netResponseDTO;
- (void)onFailureWithNetResponseDTO:(NetResponseDTO *)netResponseDTO;
- (void)triggerIfMaxRetryLimitReachedWithNetRequestDTO:(NetRequestDTO *)netRequestDTO;
- (void)onPreparedFailureDTOWithNetResponseDTO:(NetResponseDTO *)netResponseDTO
                        withFailureResponseDTO:(FailureResponseDTO *)failureResponseDTO;
- (void)onDataContractViolationWithNetResponseDTO:(NetResponseDTO *)netResponseDTO;
+ (NSString *)generateEndPointWithNSString:(NSString *)relativeUrl;
+ (NSString *)generateEndPointWithNSString:(NSString *)baseApiUrl
                              withNSString:(NSString *)relativeUrl;
- (void)updateSyncTimingsFromLocalWithSyncEntitiesDTO:(SyncEntitiesDTO *)entitiesDTO
                                                                  withNSString:(NSString *)url;
- (void)updateSyncTimingsFromRemoteWithSyncEntitiesDTO:(SyncEntitiesDTO *)entitiesDTO
                                                                   withNSString:(NSString *)url
                                                                    withLongInt:(long long int)lastSyncedDateTime;
@end

typedef SyncGateway ComJvanilaMobileSyncSyncGateway;
