//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/sync/events/SyncAdapterReadyToUseEvent.java
//
//

#import "Emulation.h"
#import "DataObject.h"

@interface SyncAdapterReadyToUseEvent : DataObject {
}

+ (NSString *)CLASS_NAME;
@end

typedef SyncAdapterReadyToUseEvent ComJvanilaMobileSyncEventsSyncAdapterReadyToUseEvent;
