//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/core/objectflavor/VanilaObject.java
//
//

#import "Emulation.h"
#import "IVanilaObject.h"

@interface VanilaObject : NSObject < IVanilaObject > {
}

- (NSString *)getClassName;
- (NSString *)stringify;
@end

typedef VanilaObject ComJvanilaCoreObjectflavorVanilaObject;
