//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/core/VanilaNotification.java
//
//

@protocol IGenericList;

#import "Emulation.h"
#import "DataObject.h"

@interface VanilaNotification : DataObject {
 @public
  NSString *message_;
  NSString *notificationId_;
  NSString *groupId_;
  id<IGenericList> actionList_;
}

@property (nonatomic, copy) NSString *message;
@property (nonatomic, copy) NSString *notificationId;
@property (nonatomic, copy) NSString *groupId;
@property (nonatomic, strong) id<IGenericList> actionList;

+ (int)NOTIFY_POLICY_OVERWRITE;
+ (void)setNOTIFY_POLICY_OVERWRITEWithInt:(int)NOTIFY_POLICY_OVERWRITE;
+ (int)NOTIFY_POLICY_STACK;
+ (void)setNOTIFY_POLICY_STACKWithInt:(int)NOTIFY_POLICY_STACK;
- (id)init;
- (BOOL)isEqual:(id)o;
- (NSUInteger)hash;
@end

typedef VanilaNotification ComJvanilaMobileCoreVanilaNotification;
