//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/core/VanilaNotificationAction.java
//
//

@protocol IGenericMap;

#import "Emulation.h"
#import "VanilaObject.h"

@interface VanilaNotificationAction : VanilaObject {
 @public
  NSString *action_;
  NSString *optionalNativeClassToLaunch_;
  id<IGenericMap> params_;
}

@property (nonatomic, copy) NSString *action;
@property (nonatomic, copy) NSString *optionalNativeClassToLaunch;
@property (nonatomic, strong) id<IGenericMap> params;

@end

typedef VanilaNotificationAction ComJvanilaMobileCoreVanilaNotificationAction;
