//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/jvanila/mobile/location/VanilaLocation.java
//
//

#import "Emulation.h"
#import "DataObject.h"

@interface VanilaLocation : DataObject {
 @public
  double latitude_;
  double longitude_;
  double altitude_;
  double speed_;
  double bearing_;
  double distance_;
  double accuracy_;
  long long int locationTime_;
  long long int systemTime_;
  NSString *provider_;
  int noOfSatellitesInFix_;
  NSString *geoAddress_;
  NSString *label_;
}

@property (nonatomic, assign) double latitude;
@property (nonatomic, assign) double longitude;
@property (nonatomic, assign) double altitude;
@property (nonatomic, assign) double speed;
@property (nonatomic, assign) double bearing;
@property (nonatomic, assign) double distance;
@property (nonatomic, assign) double accuracy;
@property (nonatomic, assign) long long int locationTime;
@property (nonatomic, assign) long long int systemTime;
@property (nonatomic, copy) NSString *provider;
@property (nonatomic, assign) int noOfSatellitesInFix;
@property (nonatomic, copy) NSString *geoAddress;
@property (nonatomic, copy) NSString *label;

+ (NSString *)CLASS_NAME;
- (id)init;
@end

typedef VanilaLocation ComJvanilaMobileLocationVanilaLocation;
