//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/domain/sync/dtos/AssociationDTO.java
//
//

#import "AssociationDTO.h"

@implementation AssociationDTO

static NSString * CLASS_NAME_;

@synthesize CRUDOperation = CRUDOperation_;
@synthesize lhs_uuid = lhs_uuid_;
@synthesize rhs_uuid = rhs_uuid_;

+ (NSString *)CLASS_NAME {
  return CLASS_NAME_;
}

- (id)init {
  if ((self = [super init])) {
    CRUDOperation_ = @"U";
  }
  return self;
}

- (id<ICloneableObject>)deepClone {
  AssociationDTO *that = [[AssociationDTO alloc] init];
  that.lhs_uuid = self.lhs_uuid;
  that.rhs_uuid = self.rhs_uuid;
  return that;
}

+ (void)initialize {
  if (self == [AssociationDTO class]) {
    {
      CLASS_NAME_ = NSStringFromClass([AssociationDTO class]);
    }
  }
}

- (void)copyAllPropertiesTo:(id)copy {
  
  AssociationDTO *typedCopy = (AssociationDTO *) copy;
  typedCopy.CRUDOperation = CRUDOperation_;
  typedCopy.lhs_uuid = lhs_uuid_;
  typedCopy.rhs_uuid = rhs_uuid_;
}

@end
