//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/domain/sync/dtos/EntityJsonDTO.java
//
//

#import "EntityJsonDTO.h"

@implementation EntityJsonDTO

static NSString * CLASS_NAME_;

@synthesize CRUDOperation = CRUDOperation_;
@synthesize entity_uuid = entity_uuid_;
@synthesize entity_group = entity_group_;
@synthesize entity_class = entity_class_;
@synthesize entity_json = entity_json_;
@synthesize sort_by = sort_by_;
@synthesize entity = entity_;

+ (NSString *)CLASS_NAME {
  return CLASS_NAME_;
}

- (id)init {
  if ((self = [super init])) {
    CRUDOperation_ = @"U";
  }
  return self;
}

- (BOOL)isEqual:(id)o {
  if (self == o) return YES;
  if (o == nil || [self class] != [o class]) return NO;
  EntityJsonDTO *that = (EntityJsonDTO *) o;
  if (entity_uuid_ != nil ? ![entity_uuid_ isEqual:that.entity_uuid] : that.entity_uuid != nil) return NO;
  return entity_group_ != nil ? [entity_group_ isEqual:that.entity_group] : that.entity_group == nil;
}

- (NSUInteger)hash {
  NSUInteger result = entity_uuid_ != nil ? [entity_uuid_ hash] : 0;
  result = 31 * result + (entity_group_ != nil ? [entity_group_ hash] : 0);
  return result;
}

+ (void)initialize {
  if (self == [EntityJsonDTO class]) {
    {
      CLASS_NAME_ = NSStringFromClass([EntityJsonDTO class]);
    }
  }
}

- (void)copyAllPropertiesTo:(id)copy {
  
  EntityJsonDTO *typedCopy = (EntityJsonDTO *) copy;
  typedCopy.CRUDOperation = CRUDOperation_;
  typedCopy.entity_uuid = entity_uuid_;
  typedCopy.entity_group = entity_group_;
  typedCopy.entity_class = entity_class_;
  typedCopy.entity_json = entity_json_;
  typedCopy.sort_by = sort_by_;
  typedCopy.entity = entity_;
}

@end
