//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/domain/sync/dtos/EntityJsonDTO.java
//
//

#import <jVanila/jvanila.h>


#define EntityJsonDTO_serialVersionUID 1

@interface EntityJsonDTO : DataObject {
 @public
  NSString *CRUDOperation_;
  NSString *entity_uuid_;
  NSString *entity_group_;
  NSString *entity_class_;
  NSString *entity_json_;
  long long int sort_by_;
  DataObject *entity_;
}

@property (nonatomic, copy) NSString *CRUDOperation;
@property (nonatomic, copy) NSString *entity_uuid;
@property (nonatomic, copy) NSString *entity_group;
@property (nonatomic, copy) NSString *entity_class;
@property (nonatomic, copy) NSString *entity_json;
@property (nonatomic, assign) long long int sort_by;
@property (nonatomic, strong) DataObject *entity;

+ (NSString *)CLASS_NAME;
- (id)init;
- (BOOL)isEqual:(id)o;
- (NSUInteger)hash;
@end

typedef EntityJsonDTO ComHomeawayHomeawayplacesDomainSyncDtosEntityJsonDTO;
