//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/sync/dtos/StaticMapMarkerDTO.java
//
//

#import "StaticMapMarkerDTO.h"

@implementation StaticMapMarkerDTO

static NSString * CLASS_NAME_;

@synthesize CRUDOperation = CRUDOperation_;
@synthesize color = color_;
@synthesize latitude = latitude_;
@synthesize longitude = longitude_;
@synthesize label = label_;

+ (NSString *)CLASS_NAME {
  return CLASS_NAME_;
}

- (id)init {
  if ((self = [super init])) {
    CRUDOperation_ = @"U";
  }
  return self;
}

+ (void)initialize {
  if (self == [StaticMapMarkerDTO class]) {
    {
      CLASS_NAME_ = NSStringFromClass([StaticMapMarkerDTO class]);
    }
  }
}

- (void)copyAllPropertiesTo:(id)copy {
  
  StaticMapMarkerDTO *typedCopy = (StaticMapMarkerDTO *) copy;
  typedCopy.CRUDOperation = CRUDOperation_;
  typedCopy.color = color_;
  typedCopy.latitude = latitude_;
  typedCopy.longitude = longitude_;
  typedCopy.label = label_;
}

@end
