//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/sync/dtos/StaticMapMarkerDTO.java
//
//

#import <jVanila/jvanila.h>


@interface StaticMapMarkerDTO : DataObject {
 @public
  NSString *CRUDOperation_;
  NSString *color_;
  double latitude_;
  double longitude_;
  NSString *label_;
}

@property (nonatomic, copy) NSString *CRUDOperation;
@property (nonatomic, copy) NSString *color;
@property (nonatomic, assign) double latitude;
@property (nonatomic, assign) double longitude;
@property (nonatomic, copy) NSString *label;

+ (NSString *)CLASS_NAME;
- (id)init;
@end

typedef StaticMapMarkerDTO ComHomeawayHomeawayplacesSyncDtosStaticMapMarkerDTO;
