//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/homeaway/homeawayplaces/sync/dtos/StaticMapRequestDTO.java
//
//



#import <jVanila/jvanila.h>


#define StaticMapRequestDTO_serialVersionUID 1

@interface StaticMapRequestDTO : DataObject {
 @public
  NSString *CRUDOperation_;
  double centerLatitude_;
  double centerLongitude_;
  int zoomLevel_;
  int width_;
  int height_;
  NSString *entityName_;
  NSString *locationPoints_;
  double radius_;
  id<IGenericList> markerList_;
}

@property (nonatomic, copy) NSString *CRUDOperation;
@property (nonatomic, assign) double centerLatitude;
@property (nonatomic, assign) double centerLongitude;
@property (nonatomic, assign) int zoomLevel;
@property (nonatomic, assign) int width;
@property (nonatomic, assign) int height;
@property (nonatomic, copy) NSString *entityName;
@property (nonatomic, copy) NSString *locationPoints;
@property (nonatomic, assign) double radius;
@property (nonatomic, strong) id<IGenericList> markerList;

+ (NSString *)CLASS_NAME;
- (id)init;
@end

typedef StaticMapRequestDTO ComHomeawayHomeawayplacesSyncDtosStaticMapRequestDTO;
